Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Fixed UI Bug related to nav bar not being `.inline`
=> Fix the fat nav bar

Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/Feed/FeedTracker.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Lazy Load Expanded Post.swift, Mlem/Views/Tabs/Profile/User View.swift
Made sure the Env Objects are always set correctly
From the Profile page and with every navigation
=> Made sure the Env Objects are always set correctly

Mlem/Views/Shared/Composer/PostComposerView.swift
Fixes a label alignment issue on the post composer that was driving me nuts
=> Fixed an issue with alignment on the post composer

Mlem.xcodeproj/project.pbxproj, Mlem/API/Models/Comments/APICommentReport.swift, Mlem/API/Models/Comments/APICommentReportView.swift, Mlem/API/Models/Posts/APIPostReport.swift, Mlem/API/Models/Posts/APIPostReportView.swift, Mlem/API/Requests/Comment/CreateCommentReport.swift, Mlem/API/Requests/Post/CreatePostReport.swift, Mlem/Logic/Participating/Report Post or Comment.swift, Mlem/Views/Shared/Composer/ReportComposerView.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item Logic.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift
- #3
This PR adds reporting for posts and comments via a similar popup sheet as posting a new post.
It also adds backing networking calls for those scenarios.
n/a
---
fixes #3
=> Added report comment and post API calls

Mlem/Views/Shared/Composer/PostComposerView.swift
- #176
Updates the logic in the post composer to only require titles (because that's how Lemmy works).
This really simplified some of the checks, which is nice.
I also updated the placeholder text to tell users the other fields are optional.
n/a
---
(fixes #176)
=> Updated new posts to only require a title (fixes #176)

Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/NSFW Tag.swift
- fixes #187
The state wasn't hooked up as a binding, now it is.
n/a
n/a
=> Fixed NSFW toggle on post composer (fixes #187)

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Stickied Tag.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Compact Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Large Post.swift
- fixes #161
The NSFW tag fell off the bus on the move to the new post format, this puts it back on the bus!
I also re-added the sticky state and made the pins green for community and red for local pins.
n/a
=> Re-adds NSFW label and sticky state to large posts (fixes #161)

Mlem/Views/Tabs/Feed Root.swift
Just fixing a small spelling mistake.
Just a spelling mistake.
-- None --
=> Fixing minor spelling mistake (brewos -> browse)

Mlem/Views/Shared/Links/User Profile Label.swift
- n/a
Updating the list to be accurate.
n/a
n/a
=> Updated team member list

Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift
Grouped the account items.
Updated add account label.
=> Fixed some issues with VO on the accounts page

Mlem/Views/Tabs/Settings/Settings View.swift, README.md
- n/a
Updated links to the latest and greatest.
n/a
n/a
=> Removed lemmy link and added Github link

Mlem/API/APIClient.swift, Mlem/Logic/Participating/SendPrivateMessage.swift, Mlem/Models/ReplyTos/ReplyToFeedPost.swift, Mlem/Views/Tabs/Feed Root.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
- No issue, just new warnings in the project
A small PR to address a couple of warnings that have crept into the project.
=> Fix - various new project warnings

README.md
=> Update README.md to vlemmy site

Mlem/API/APIClient.swift
Implemented catching 500 errors, this seems to be an used by Lemmy.world and Beehaw when they are undergoing maintenance.
=> Handle Instance Offline

Mlem/ContentView.swift, Mlem/Views/Tabs/Feed Root.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Subscribe Button.swift
I've added an alert that shows up the first time you open the app to notify users of the community change.
It features a button to go to the community, a button to swap subscriptions over, and a dismiss.
This code is jank and I really kinda slapped it together, but it works.
https://github.com/mlemgroup/mlem/assets/44140166/144a2e00-d987-42cf-92c9-dd0689f31f42
=> Added Alert for New Community

Mlem/Views/Tabs/Feed Root.swift
Added escape action to the alert overlay
=> added accessibility escape

Mlem/Models/ReplyTos/ReplyToComment.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item Logic.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/CommentBodyView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/ExpandedPostLogic.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Compact Post.swift, Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Reply.swift
- #218 
Adds a reply button to the interaction bar. Moves some things around to make it easy to tap.
=> Added reply to interaction bar

Mlem/Views/Shared/Composer/MessageComposerView.swift, Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift, Mlem/Views/Shared/Links/User Profile Link.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Mention View.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Message View.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Reply View.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/CommentBodyView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/NSFW Tag.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Stickied Tag.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/UltraCompactPost.swift, Mlem/Views/Tabs/Profile/User View.swift
- Addressing feature regression
Fixes a couple little things that were wrong with compact mode:
- In non-community feeds, posts now display community, not username
- Updated info bar to align with other post modes
- Post view now has the proper "undo upvote/downvote" swipey icon
Additionally tweaked the UserProfileLabel and CommunityLabelView to now take an optional `overrideShowAvatar: Bool?`, which, if defined, shows or hides the avatar; if not given, the label will default to app settings. Updated the links to match.
=> Compact Tweaks

Mlem/Feed/FeedTracker.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Made the feed load faster!
Made the feed load much faster, and removed the annoying slug when new posts load
this was done by moving most of the data processing (like deduping, filtering, merging) into the background
(and pre-allocating space for the de-duping function)
This is a part of smaller speed focused PRs, al split from the "Speed is key" master PR
=> Speed Pt.1 - Feed Fever:

README.md
Reset community links back to lemmy.ml
=> updated community links again

Mlem/ContentView.swift, Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/MlemApp.swift, Mlem/Models/Trackers/Favorite Community Tracker.swift, Mlem/Models/Trackers/Filters Tracker.swift, Mlem/Models/Trackers/Saved Account Tracker.swift, Mlem/Views/Shared/Links/User Profile Label.swift, Mlem/Views/Tabs/Feed Root.swift, Mlem/Window.swift
removed the annoying slow startup
Made all the trackers load from disk on init, that way need need to publish less changes to swiftUI making their data available much earlier
Changed the startup sequence to load a community view much earlier
=> Speed Pt.2 - Trackers Glory

Mlem.xcodeproj/project.pbxproj, Mlem/API/Models/Community/APICommunityView.swift, Mlem/App Constants.swift, Mlem/ContentView.swift, Mlem/Extensions/Int.swift, Mlem/Logic/File Management/Decode Data from File.swift, Mlem/Models/Trackers/Community Search Result Tracker.swift, Mlem/Models/Trackers/RecentSearchesTracker.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Loading View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community Search/Community Search View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community Search/Components/Community Search Field.swift, Mlem/Views/Tabs/Search/Search View.swift, Mlem/Window.swift
- Fixed #88 
Adds a new search tab to the bottom bar.
I implemented paging on my own because I didn't think the feed tracker stuff would scale to multiple result types at the moment.  It's.... not pretty.
A few other side bits:
- Added utility to `Int` to print things like `1.2k` and `1.1m`
- Updated search tracker to use views so we can display how many subscribers communities have
- This does NOT touch the existing search, but it should be downgrade to swapping between "Subscribed", "Local", and "All" (no search)
=> Added search tab for communitiyes (fixes #88)

Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Logic/Time Parser.swift, Mlem/Views/Shared/TimestampView.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Mention View.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Message View.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Reply View.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Interaction Bar.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/UltraCompactPost.swift
- #33
Addresses #33 to make the date on posts and comments shorter. It now uses `s`, `m`, `h`, `d`, `w`, `mo`, `y`.
Also abstracted the timestamp to a `TimestampView` struct for easier reusability.
=> Date format

Mlem.xcodeproj/project.pbxproj, Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/Extensions/OperationQueue - Easy init.swift, Mlem/MlemApp.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Shared/Cached Image With Nsfw Filter.swift, Mlem/Views/Tabs/Settings/Components/Views/General.swift
This PR replaces our old image system with the Nuke library!
Nuke does things like decode images in the background, and in a very multithreaded way,
Makes scrolling the feed silky smooth
=> Nuke image Preloading

Mlem.xcodeproj/project.pbxproj, Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/Extensions/OperationQueue - Easy init.swift, Mlem/MlemApp.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Shared/Cached Image With Nsfw Filter.swift, Mlem/Views/Shared/Website Icon Complex.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Large Post.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance.swift, Mlem/Views/Tabs/Settings/Components/Views/General.swift
- Ongoing effort to smooth out the feed
This PR adds preloading for user and community avatars. It also revamps the `WebsiteIconComplex` to be less line-y and more Apple (and *way* nicer on the backend)
=> More preloading + new website complex

Mlem.xcodeproj/project.pbxproj, Mlem/API/Requests/Person/BlockPerson.swift, Mlem/Feed/FeedTracker.swift, Mlem/Logic/Participating/BlockPersonLogic.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Tabs/Feed Root.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift
Implement Block User API
Add Block User Button
Block User Toast
Update Post Tracker
=> Implemented User Blocking

Mlem/Views/Shared/Composer/CommentComposerView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Sidebar Header Label.swift, Mlem/Views/Tabs/Profile/Profile View.swift
Some minor "improvements" to the profile header design.
=> Tweaked the Profile View

Mlem/Views/Shared/Links/User Profile Label.swift
- n/a
My main was on vlemmy (RIP).  Trying my own instance from now on, we'll see how long I last :)
n/a
n/a
=> Updated dev list

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Forgot to remove this before merging.
=> Removed dead/commented out code

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Accessibility improvements for feed picker
when in a community, activating will show sidebar
=> Small improvements to the feed picker

Mlem.xcodeproj/project.pbxproj, Mlem/ContentView.swift, Mlem/Mlem.entitlements, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Profile/Profile View.swift, Mlem/Views/Tabs/Settings/Components/Views/AlternativeIconCell.swift, Mlem/Views/Tabs/Settings/Settings View.swift
Just enabled iPad as a build target
---
Related: #105
=> Initial iPad support

Mlem/Views/Shared/Cached Image With Nsfw Filter.swift
=> Fixed image placeholder height

Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Extensions/Environment - EasterFlagSetter.swift, Mlem/Logic/Easter/Easter Rewards.swift, Mlem/Logic/Easter/RecognizedLemmyInstances.swift, Mlem/Logic/File Management/Decode Data from File.swift, Mlem/Models/Settings/AlternativeIcon.swift, Mlem/Models/Trackers/EasterFlagsTracker.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Settings/Components/Views/Alternative Icons.swift, Mlem/Window.swift
- #268 
Added a fancy easter tracker to keep track of all the easter flags!
Added a dictionary  of easter rewards so if you do something cool we can let you know what owe unlocked for you
Added a dictionary  of icons that should be kept behind some easter flag
(this uses a fake trigger ofc the real trigger is entering the beehew instance for now ;) )
https://github.com/mlemgroup/mlem/assets/6067331/b00e9c18-3a03-4432-946b-145f16c62971
=> Added a fancy easter eggs system

Mlem/App Constants.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Header.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Headline Post.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/UltraCompactPost.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance.swift, Mlem/Views/Tabs/Settings/Components/Views/Detail Views/CustomizePostView.swift
Previously the default settings had thumbnails and instances hidden, which is probably not what people generally want--this PR changes those defaults.
=> fixed some default settings

Mlem/Logic/File Management/Decode Data from File.swift
fixes a tiny oppsie that prevented the easter flags to be loaded from disk and displayed the easter message repeatedly
=> Fixed loading EasterFlags

Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Extensions/Swipey Actions.swift, Mlem/Logic/Participating/BlockPersonLogic.swift, Mlem/Logic/Participating/Delete Post or Comment.swift, Mlem/Logic/Participating/MarkCommentReplyAsRead.swift, Mlem/Logic/Participating/MarkPersonMentionAsRead.swift, Mlem/Logic/Participating/MarkPrivateMessageAsRead.swift, Mlem/Logic/Participating/Post Comment.swift, Mlem/Logic/Participating/Post Post.swift, Mlem/Logic/Participating/Rate Post or Comment.swift, Mlem/Logic/Participating/Report Post or Comment.swift, Mlem/Logic/Participating/Report Private Message.swift, Mlem/Logic/Participating/Save Comment.swift, Mlem/Logic/Participating/Save Post.swift, Mlem/Logic/Participating/SendPrivateMessage.swift, Mlem/Singletons/Haptic Manager.swift, Mlem/Views/Shared/TokenRefreshView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Block Community Button.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Components/Subscribe Button.swift
- fixes #37 
- fixes #56 
This PR moves all haptic management into a singleton class, `HapticManager`, which is accessed using `HapticManager.shared` and offers a set of haptic responses.
All existing haptic calls in the app have been replaced with calls to `HapticManager`.
It additionally defines several custom haptics--I'd try to describe them, but you've really just gotta feel 'em for yourself.
=> Unified haptics

Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/TokenRefreshView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/NSFW Tag.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Add Account View.swift
Cleans up design around the Reauth Screen (@mormaer told me to)
Improves Dynamic Text in a few areas.
Leaving in Draft till 1.0 is 🚢
=> Re-auth Screen Design Updates

Mlem/MlemApp.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Website Icon Complex.swift
- #31
This PR adds basic QuickLook support. allowing things like Zooming an image, downloading it, sharing, live text, and markup
https://github.com/mlemgroup/mlem/assets/6067331/2734dc0c-74aa-4c5d-a1b4-960637e22df7
=> Added QuickLook support

Mlem.xcodeproj/project.pbxproj, Mlem/ContentView.swift, Mlem/Custom Tab Bar/FancyTabBar.swift, Mlem/Custom Tab Bar/FancyTabBarLabel.swift, Mlem/Custom Tab Bar/FancyTabBarSelection.swift, Mlem/Custom Tab Bar/FancyTabBarSelectionEnvironmentKey.swift, Mlem/Custom Tab Bar/FancyTabItemLabelBuilder.swift, Mlem/Custom Tab Bar/FancyTabItemPreferenceKeys.swift, Mlem/Custom Tab Bar/FancyTabItemViewModifier.swift, Mlem/Enums/TabSelection.swift, Mlem/Models/Saved Account.swift, Mlem/Views/Tabs/Feed Root.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance.swift, Mlem/Window.swift
- [] This PR addresses one or more open issues that were assigned to me:
This PR replaces the standard tab bar with a custom one which we can do all sorts of fun stuff to.
Implements the account quick-switcher, and sets up #60 and #246 
https://github.com/mlemgroup/mlem/assets/44140166/8e84e834-0d1b-46b2-a601-c1ae9220d0a9
=> Fancy Tab Bar

Mlem/Views/Shared/TokenRefreshView.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Add Account View.swift
Redesigned the login screen to be a bit easier on the eyes
https://github.com/mlemgroup/mlem/assets/864259/fe0872fd-5c9d-4b66-ba20-43fabcbf7c02
=> Redesigned Login Screen

Mlem.xcodeproj/project.pbxproj
Just bumping version to 1.0.1 so we can get TF builds again.
=> Version Bump for Testflight

Mlem/Extensions/Swipey Actions.swift, Mlem/Singletons/Haptic Manager.swift
- Ongoing refinement of app feel
This PR subtly tweaks the haptic and the swipe animation to make the app feel better.
- Swipe min drag distance has been reduced from 30 to 20
- Swipe animation response has been reduced from 0.3 to 0.25
- Added haptic feedback for crossing "backwards" over a swipey action border
- Added `mushyInfo` haptic
- Added `firmerInfo` haptic. It is the same haptic as the second click of `gentleSuccess`.
- `gentleInfo` haptic is a little less gentle. It is now the same haptic as the first click `gentleSuccess`.
- Changed the haptic for crossing from short -> long swipe from `gentleInfo` to `firmerInfo`. The feel of pulling the swipe is now a slowed down version of the success haptic.
- Fixed a bug where haptics were playing twice when crossing swipe boundaries
=> Touchy feely stuff

CONTRIBUTING.md, README.md
- #163 
Updated README and CONTRIBUTING. These have been long overdue a rewrite imo. Let me know what you think, and whether there's anything else you think we should add.
=> Update Readme & Contributing

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift
Added some missing .fancyTabScrollCompatible
=> added scroll compatibility to feeds and expanded post

Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Posts/Components/NSFW Tag.swift
Fixes the NSFW toggle in the New Post sheet not matching dark mode. Closes #290.
=> NSFW toggle changes

Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/Views/Tabs/Feeds/Feed View Logic.swift, Mlem/Views/Tabs/Feeds/Feed View.swift
Fixes an issue where navigating back to the feed caused a refresh.
=> fixed problem where navigating back to the feed caused a refresh

Mlem/Views/Shared/Components/Interaction Bars/Post Interaction Bar.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
Exactly what it says on the tin
=> Turned score in infostack on by default

Mlem/App Constants.swift, Mlem/Views/Tabs/Feeds/Community List/Community List View.swift, Mlem/Views/Tabs/Profile/User View.swift
This PR changes two icons per Slack chat:
- Change account in profile page
- Federated symbol name
=> changed a couple icons

Mlem/Enums/Settings/Vote Complex Style.swift, Mlem/Views/Shared/Components/Buttons/Vote Complex/Vote Complex.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Comment/CommentSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
After internal discussion, reinstated the vote complexes.
=> reinstated vote complexes

Mlem/Views/Shared/Posts/Feed Post.swift
- closes #374 
Temporarily removes the conditional padding to make iPad layout display as "cards"--that broke the visuals of swipey actions pretty hard, so until we figure out what we want to do long-term, this makes the iPad layout visually consistent with the iPhone layout
=> Hotfix iPad layout

Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift
- closes #420 
This PR gets rid of the microhangs in the feed by migrating user and community avatars to CachedImage.
=> Banished microhangs from the feed

Mlem/Views/Shared/Components/Interaction Bars/Post Interaction Bar.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift, Mlem/Views/Shared/Website Icon Complex.swift
- Nope lol
This PR fixes some minor defects ahead of a TF release:
- Put haptics back in for saving posts (whoops)
- Made large post obey the same read rules as compact (opening image or clicking on link marks post as read)
=> Made largePost obey same read marking rules as compact and headline

Mlem.xcodeproj/project.pbxproj, Mlem/Custom Tab Bar/FancyTabBar.swift
- closes #440 
Puts the fancy tab bar at the bottom of the sort priority order so that it works properly with top of screen/bottom of screen a11y gestures
=> Fixed accessibility ordering of fancy tab bar

Mlem.xcodeproj/project.pbxproj, Mlem/ContentView.swift, Mlem/Custom Tab Bar/FancyTabBar.swift, Mlem/Custom Tab Bar/FancyTabBarLabel.swift, Mlem/MlemApp.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift, Mlem/Views/Shared/Markdown View.swift
- closes #458 
Fixes an issue where the username was not properly displaying in compact mode.
Also takes the opportunity to make the following changes:
- Scaling of the flair is now done using `.imageScale` to make it small in trailing mode
- Flair image is no longer disabled when instance location is `.trailing`
- Avatar URL now always takes the Icon64 URL, since that's what gets prefetched
- Avatar size is now a computed var instead of a function and represented as a `CGSize`
- Instance is now `UIColor.tertiaryLabel` instead of `.secondary` with opacity 0.6
Also made some minor miscellaneous tweaks:
- Fix font size in `.mlemDeemphasized` to be consistent with `.mlem`
- Tab switch animation has been greatly sped up
- Nav bar swipe up is disabled on devices with a home button
- Added …
=> Polishing for App Store

Mlem/ContentView.swift
- #457 
Hot fix for renamed callback that didn't get merged properly.
=> - Fix renamed callback.

Mlem.xcodeproj/project.pbxproj, Mlem/API/APIClient.swift, Mlem/API/Requests/User/DeleteUser.swift, Mlem/Views/Shared/Accounts/Accounts Page.swift, Mlem/Views/Shared/Accounts/DeleteAccountView.swift
Hotfix to comply with the almighty App Review. Adds account deletion flow.
https://github.com/mlemgroup/mlem/assets/44140166/644358ac-48c2-4e6d-9814-959360b3b7f0
=> 1.0.1 Hotfix: Delete Accounts

Mlem/Models/Composers/Response Composers/Replies/ReplyToPost.swift, Mlem/Models/Composers/Response Composers/Reports/ReportPost.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
- #461 
Adds ability to minimize (collapse) a post's content when viewing as expanded post.
- Tested in light and dark modes.
- Tested in right-to-left language mode.
- Accessibility support.
https://github.com/mlemgroup/mlem/assets/2549615/f0dbc7f5-b266-43ee-8932-70962ae255cb
https://github.com/mlemgroup/mlem/assets/2549615/df4b1a8e-1b3b-47d6-969e-707544e56d05
Not so sure about the accessibility hint/label.
=> #461 collapse post content

Mlem/App Constants.swift, Mlem/Views/Shared/Comments/Comment Item Logic.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Tabs/Inbox/Feed/InteractionSwipeAndMenuHelpers.swift
Marks Report/Block menu actions as destructive.
| Currently | New |
|---|---|
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 21 49 38](https://github.com/mlemgroup/mlem/assets/20093825/333c67ff-7b52-467a-a0d1-91796fbbceed) | ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 21 49 09](https://github.com/mlemgroup/mlem/assets/20093825/7cdc463f-1447-4e76-b971-769ac7dca3c4) |
=> Marked report/block as destructive

Mlem.xcodeproj/project.pbxproj, Mlem/Views/Shared/Components/Components/Website Indicator View.swift, Mlem/Views/Shared/Components/Thumbnail Image View.swift
- closes #509 
This PR adds a little Safari icon overlay to link thumbnails.
=> Added link indicator to thumbnail

Mlem/Haptics/Haptic Manager.swift
- nope lol
Haptics were causing a slight animation hitch the first time they played (this was especially apparent when using swipe actions). This PR moves the haptic work to a background thread so they can load without interrupting the animations.
=> Moved haptics to the background to avoid initialization animation hitch

Mlem/App Constants.swift, Mlem/Views/Shared/Composer/PostDetailEditorView.swift, Mlem/Views/Shared/Composer/ResponseEditorView.swift
- None
- Make text field line limit dynamically change based on content in Post reply and Comment reply editors.
- Make text field fit up to 10 lines before requiring scrolling to see all text.
https://github.com/mlemgroup/mlem/assets/2549615/a9b1888f-dc5c-4a78-a909-3646e86232c5
=> Reply editor textfield variable line height

Mlem/Views/Tabs/Inbox/Inbox View Logic.swift
- closes #434 
Adds logic to mark replies, mentions, and messages as read when they are interacted with.
https://github.com/mlemgroup/mlem/assets/44140166/5969a337-6f73-44b8-82ae-12166b772c90
https://github.com/mlemgroup/mlem/assets/44140166/239c2313-1b81-4c50-8841-ebbf1dcc5b6e
=> Inbox operations now mark item as read

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/Mocks/ErrorDetails+Mock.swift, Mlem/Models/ErrorDetails.swift, Mlem/Views/Shared/Error View.swift
Fixed a small visual bug in the `ErrorView`, and added a `.mock()` to `ErrorDetails` for testing use in future.
=> `ErrorView` bug fix

Mlem/Models/Settings/LayoutWidgets/LayoutWidget.swift, Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift, Mlem/Models/Settings/LayoutWidgets/LayoutWidgetModel.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetView.swift
Still need to make the save system better, though... it still saves only when you press "back", and not when you switch tab
=> Allow Duplicate Interaction Bar Widgets

Mlem/Views/Shared/Components/Thumbnail Image View.swift
- Hot off the TF
This PR fixes website thumbnails not always appearing in the right place
BEFORE:
AFTER:
=> fixed wandering website icon

Mlem/Models/Trackers/Post Tracker.swift
- See below under Additional Context
When a user saves a post, this post receives an additional upvote. If the user un-saves a post, nothing happens (and they'd have to manually downvote it again)
https://github.com/mlemgroup/mlem/assets/2580019/3db9173e-4bb7-479a-bfd3-31eb5c279a57
#514 wasn't assigned to me, I just had a few minutes time, wanted to contribute and was looking for one of those `good first issue`-issues. Take it (and kindly assign me that issue) or leave it :)
=> Upvote on save (#514)

Mlem/Models/Composers/PostEditor.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Shared/Comments/Components/Embedded Post.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Shared/Posts/Lazy Load Expanded Post.swift, Mlem/Views/Tabs/Feeds/Feed View.swift, Mlem/Views/Tabs/Inbox/Inbox View.swift, Mlem/Views/Tabs/Profile/User View.swift, Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
- closes #514 
This PR adds an option in settings to enable upvote-on-save functionality.
It also performs some minor adjustments to the logic to prevent "state flickering."
=> Added option to toggle upvote on save

Mlem/Models/Trackers/Post Tracker.swift
- closes #586 
This PR fixes an issue where refresh was not loading the correct pages. The `page` value was not being updated, so later pages were being loaded and the initial pages were not--`page` is now reset to 1 before calling refresh so that the refreshed feed starts at the first page.
=> Refresh now behaves consistently

Mlem/App Constants.swift, Mlem/Views/Shared/Posts/Expanded Post.swift
=> - Add overscroll so comment jump button doesn't overlap comment item.

Mlem/App Constants.swift, Mlem/Views/Shared/Posts/Expanded Post.swift
=> Expanded Post overscroll

Mlem/Models/Trackers/Post Tracker.swift
Adds the vital line of code that makes prefetching, y'know, prefetch.
=> reinstated prefetching

Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift
=> Fix widget wizard rect bug

Mlem/Views/Shared/Components/Components/InfoStackView.swift, Mlem/Views/Shared/Components/InteractionBarView.swift
=> Fix info stack alignment

Mlem/Views/Tabs/Search/SearchHomeView.swift, Mlem/Views/Tabs/Search/SearchView.swift
Fixed a bug where results on the search homepage would occasionally disappear when navigating back to the homepage from a community/user page.
=> Fix search home page refresh bug

Mlem.xcodeproj/project.pbxproj
=> bumped version

.github/workflows/ci_build_15.yml
- n/a
Bumped the version of Xcode because GitHub's agents did.
n/a
n/a
=> Bumped Xcode version to 15.0.1

.github/workflows/ci_build_15.yml
=> Update CI device destintation

Mlem/Views/Tabs/Profile/UserFeedView.swift
- closes #738 
Fixes profile regression introduced by UserModel
=> fixed posts not showing in profile

Mlem/Views/Shared/Comments/Comment Item Logic.swift, Mlem/Views/Shared/Comments/Comment Item.swift
- Address regression caused by #726 
Adds haptics back in for comment actions
=> re-added comment haptics

Mlem.xcodeproj/project.pbxproj
=> bumped version to 1.1.2

Mlem.xcodeproj/project.pbxproj
Version bump was undone by #818. Re-bumps to 1.1.3.
=> bumped version to 1.1.3 (again)

Mlem/Models/Trackers/Post Tracker.swift
- closes #819 
Fixes refresh not properly resetting the cursor, causing refresh to effectively page forwards on 0.19 instances.
=> fixed refresh behaving poorly on 0.19

Mlem/Views/Tabs/Feeds/Feed View.swift
Fix issue where tapping on tab bar doesn't cause sidebar to hide on regular size class (e.g. iPad).
=> Tap tab bar to show/hide sidebar on iPad

Mlem/Logic/URLHandler.swift, Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
Requested on mlemapp [here](https://lemmy.ml/post/10530633). Closes #517
=> "Open Links in Default Browser" Setting

Mlem/Icons.swift, Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
=> Setting to Disable Tap-to-Collapse

Mlem/Views/Tabs/Feeds/Feed Types/AggregateFeedView.swift, Mlem/Views/Tabs/Feeds/Feed Types/CommunityFeedView.swift, Mlem/Views/Tabs/Feeds/FeedsView.swift
- closes #875
Adds tab tap navigation actions back into the feed tab
=> Reinstated feed tab navigation

Mlem/Models/Content/Community/CommunityModel.swift, Mlem/Models/Content/Post/PostModel.swift
=> Fix blocking communities from posts

Mlem/Views/Shared/Comments/Comment Item Logic.swift
=> PR 896 Rebased

Mlem/Views/Tabs/Feeds/Components/FeedHeaderView.swift
Changed "your saved posts" to "your saved posts and comments".
=> Update Saved feed caption

Mlem/Navigation/DismissAction.swift
Adds a property in Navigation that allows users to eventually specify what tab bar navigation behaviour to use.
- This PR does not contain any UI/UX changes.
=> Tab navigation behaviour

Mlem.xcodeproj/project.pbxproj, Mlem/Animations/Animations.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
=> Disable collapse animations when "Reduce Motion" is on

Mlem.xcodeproj/project.pbxproj, Mlem/Icons.swift, Mlem/Models/Content/Community/CommunityModel.swift, Mlem/Models/Trackers/ModToolTracker.swift, Mlem/Views/Shared/Moderation/ModToolSheet.swift, Mlem/Views/Shared/Moderation/Tools/AddModView.swift, Mlem/Views/Shared/UserList/ModeratorListView.swift, Mlem/Views/Tabs/Feeds/Feed Types/CommunityFeedView.swift, Mlem/Views/Tabs/Settings/Components/AccountListView.swift, Mlem/Views/Tabs/Settings/Components/SettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Account/ProfileSettingsView.swift
- closes #963
This PR adds the ability to edit the moderator list of communities the current user moderates.
https://github.com/mlemgroup/mlem/assets/44140166/91af2e75-f487-4786-ade7-667bb3175cba
https://github.com/mlemgroup/mlem/assets/44140166/d786ca05-f7c9-4a39-ba00-ffb839976a28
=> Editable Moderator List

Mlem/Temp Image Viewer/ImageSaver.swift, Mlem/Temp Image Viewer/ZoomableImageView.swift, Mlem/Views/Shared/Cached Image.swift
=> Show Image Save Error

Mlem.xcodeproj/project.pbxproj, Mlem/Views/Tabs/Profile/UserView+Logic.swift, Mlem/Views/Tabs/Profile/UserView.swift, Mlem/Views/Tabs/Search/BubblePicker/BubblePicker.swift, Mlem/Views/Tabs/Search/BubblePicker/ChildSizeReader.swift
- nope lol
This PR improves the bubble picker animation, bringing it closer in line with Apple's design. The capsule now slides smoothly between selections.
The visual effect is created by overlaying atop the black-on-white base layer an identical white-on-blue layer, which is then masked with a `Capsule` that slides to the selected item. In order to offset and size the `Capsule` correctly, each child element now reports its width and offset to the `BubblePicker` by use of the `ChildSizeReader`, which updates a preference key.
https://github.com/mlemgroup/mlem/assets/44140166/c4b66ab2-3b69-4da3-837f-19770847a237
=> Improved bubble picker animation

Mlem/Models/Content/Post/PostModel+MenuFunctions.swift
=> Prepend post title to "Select Text" popup

Mlem.xcodeproj/project.pbxproj, Mlem/App/Logic/API/API Client/ApiClient+Post.swift, Mlem/App/Logic/API/API Client/Caching/Conformance/Community+CacheExtensions.swift, Mlem/App/Logic/API/API Client/Caching/Conformance/Person+CacheExtensions.swift, Mlem/App/Logic/API/API Client/Caching/Conformance/Post+CacheExtensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APICommunity+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APICommunityView+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APIGetCommunityResponse+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APIGetSiteResponse+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APIPerson+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APIPost+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APIPostView+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APISite+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Extensions/APISiteView+Extensions.swift, Mlem/App/Logic/API/Models/Custom/Person2ApiBacker.swift, Mlem/App/Logic/API/Models/Custom/Person3ApiBacker.swift, Mlem/App/Models/Content/Post/Post2.swift, Mlem/App/Models/Content/Post/Post2Providing.swift, Mlem/App/Models/Content/User/UserStub.swift, Mlem/App/Models/Helpers/StateManager.swift, Mlem/App/Views/Root/Tabs/Feeds/FeedsView.swift, Mlem/App/Views/Root/Tabs/Profile/Profile View.swift
- Simplified `cacheId` logic
- Fixed a bug where accounts created pre-2.0 wouldn't load correctly
- Made `VoteStatusManager` into a generic `StateManager`
I may make some further tweaks to `StateManager` in another PR
=> Dev2 tweaks

Mlem.xcodeproj/project.pbxproj, Mlem/Views/Shared/Accounts/DeleteAccountView.swift, Mlem/Views/Shared/Components/Modlog/ModlogView.swift, Mlem/Views/Shared/Moderation/Tools/PurgeContentView.swift, Mlem/Views/Shared/WarningView.swift
This PR  creates a reusable warning view and uses it for the modlog, delete account, and purge content warnings.
=> Reusable warning view

Mlem/API/Internal/HierarchicalComment.swift, Mlem/Enums/Settings/CommentSortType.swift, Mlem/Logic/URLHandler.swift, Mlem/Models/Content/Post/PostModel+MenuFunctions.swift, Mlem/Models/Content/Post/PostModel.swift
- #1011 (hopefully closes)
This PR standardizes how we access `UserDefaults`, replacing all direct references with the `@AppStorage`. This may or may not put us into compliance with app review; we'll just have to submit it and see. Worst case, our codebase gets a little more consistent.
=> Replace UserDefaults with AppStorage

Mlem/Models/Content/Post/PostModel+MenuFunctions.swift, Mlem/Models/Content/User/UserModel+MenuFunctions.swift, Mlem/Views/Tabs/Profile/UserView.swift
- Fix blocking from `UserView` (Closes #1021).
- Made `UserView`"Unblock" action non-destructive to match the rest of the app.
- Made post "Block" action popup show in red rather than blue.
=> Fix user blocking

Mlem/Models/Content/Instance/InstanceModel+Uptime.swift
This PR adds `toast.ooo` and `szmer.info` to the list of lemmy-status' supported instances.
=> more instance uptime

Mlem.xcodeproj/project.pbxproj, Mlem/API/APIClient/APIClient+Instance.swift, Mlem/API/Models/Site/APIMyUserInfo.swift, Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift, Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift, Mlem/Models/Content/Community/CommunityModel.swift, Mlem/Models/Content/Instance/InstanceModel+MenuFunctions.swift, Mlem/Models/Content/Instance/InstanceModel.swift, Mlem/Models/Content/Post/PostModel+MenuFunctions.swift, Mlem/Models/Content/User/UserModel+MenuFunctions.swift, Mlem/Models/Content/User/UserModel.swift, Mlem/Navigation/Destination Values/SettingsValues.swift, Mlem/Views/Shared/CommunityList/CommunityListRow.swift, Mlem/Views/Shared/CommunityList/CommunityListRowBody.swift, Mlem/Views/Shared/Loading View.swift, Mlem/Views/Shared/UserList/UserListRow.swift, Mlem/Views/Shared/UserList/UserListRowBody.swift, Mlem/Views/Tabs/Profile/UserView+Logic.swift, Mlem/Views/Tabs/Settings/Components/Views/Account/AccountSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Account/BlockListView+Logic.swift, Mlem/Views/Tabs/Settings/Components/Views/Account/BlockListView.swift
- Added a blocklist under account settings.
- Added "blocked"/"unblocked" notifications when blocking from user/community pages.
- All "blocked" notifications now show a checkmark rather than a cross when successful.
=> Block List

Mlem/Views/Shared/Comments/Components/CommentBodyView.swift
- closes #470 
This PR fixes "Comment was deleted/removed" showing even when the comment is deleted.
=> Fixed deleted/removed comments not properly collapsing

Mlem.xcodeproj/project.pbxproj, PrivacyInfo.xcprivacy
Conformance App Store requirements
=> Cite CA92.1 for UserDefaults

Mlem/Models/Batchers/MarkReadBatcher.swift, Mlem/Window.swift
=> Fix `"couldnt_mark_post_as_read"` when switching accounts

CONTRIBUTING.md, Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Updated CONTRIBUTING.md:
- Tidied structure
- Added `MainActor` convention
- Added `Hashable` `enum` convention
=> Updated CONTRIBUTING.md

Mlem.xcodeproj/project.pbxproj, Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/App/Models/Account/GuestAccount.swift, Mlem/App/Views/Shared/Accounts/AccountListView+Logic.swift
This is a sister PR to MlemMiddleware's thread safe caching. No significant changes.
=> Thread Safe Caching

Mlem.xcodeproj/project.pbxproj
Merges master back into dev and bumps version to 1.3.3
=> 1.3.3 Version Bump

Mlem.xcodeproj/project.pbxproj, Mlem/Views/Tabs/Search/PasteLinkButtonView.swift, Mlem/Views/Tabs/Search/SearchView.swift
Closes #1103
This is the best place I could think to put it, lmk if you think somewhere else would be better:
=> Add Paste Link from Clipboard Button

Mlem/App/Views/Shared/FancyScrollView.swift
=> Rewrite FancyScrollView to avoid SwiftUIIntrospect
