mlemgroup/mlem

Mlem/Views/Shared/Cached Image With Nsfw Filter.swift
- fixed #168
Disabled hit detection on image in CachedImageWithNsfwFilter. Something about the ZStack (I think) was causing the hit bounds detection to ignore clipping. Tapping anywhere on the image still works because the onTapGesture applies to the parent view.
=> fixed large posts making web complex tappable *everywhere*

Mlem/Models/Saved Account.swift
- #199
This addresses the concern raised in #199
As we're now storing the access token in the keychain (and retrieving it during start-up) we should not be storing it in JSON. This change ensures we write `"redacted"` into the file on disk instead of the real token.
The way we read/write to disk at start-up could do with some TLC, but for now this addresses the immediate concern.
=> fix #199 - ensure access token is not written to insecure disk location

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/URL - Lemmy Image Parameters.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift
- n/a
This PR updates profile and community avatars to use 32px or 64px avatars depending on their rendered size.
The result is much smoother scrolling with slight degradation of icons visually.
n/a
Probably could play with the format of the image as well (png, etc.)
=> Optimized embedded avatar images to be the needed size

Mlem/Views/Tabs/Search/Search View.swift
The new search tab is awesome but the in-app link handling was a bit forgotten!
Now when you press a Lemmy link while in the search tab the link will open in app
=> - fixed Search doesn't handle in-app link resolution

Mlem/Extensions/View - Handle Lemmy Links.swift
- #24 
Made a few changes to the way I'm handling community links to clean them out more before we try resolving them,
this fixed the example page from the issue failing to open the community in app:
https://lemmy.guide/link?target=!programmer_humor@programming.dev
https://lemmy.guide/link?target=!liftoff@lemmy.world
This is mostly a temp patch to a system that needs some real work, I think this patch would cover most real-world cases until we have time to really look into the federated way of handling links (plus I really want the example links working, it feel unprofessional to leave them broken 🤣 )
=> - made deep-linking handling for community links much much more reliable

Mlem/Extensions/Swipey Actions.swift
Certain feed posts were getting extra padding with swipey actions enabled, leading to the background being visible around the post.
This PR refactors the swipey actions to use a `.background` instead of a `ZStack` to display the background.
=> fixed bad swipey action behavior on certain feed posts

Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift
This PR fixes some line breaking issues with Text elements in `CommuntiyFeedRowView`. Previously the Text views were concatenated using an `HStack`. I changed that to use native `Text` concatenation using the + operator.
Note: The Operating Systems community row.
Before:
After:
N/A
=> Fix Text Line Break in CommuntiyFeedRowView

Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift, Mlem/Views/Tabs/Profile/User View.swift
This PR fixes an issue where the reply modal wasn't popping up on FeedPosts.
FeedPost now no longer provides its own reply sheet; rather, it accepts a `@Binding ConcreteRespondable?` which triggers a response sheet in its parent view.
=> Fixed reply modal not appearing for FeedPost

Mlem/API/Models/Community/APICommunity.swift, Mlem/Enums/FeedType.swift, Mlem/Logic/File Management/Decode Data from File.swift, Mlem/Logic/Get Favorited Communities.swift, Mlem/Models/Favorite Community.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift
Made APICommunity and FavoriteCommunity Comparable, this should fix lots of sorting issues
Changed Feed Icons
Renamed All Known back to All. This matches Lemmy Web
=> Fixed Sort order of Communities to include instance

Mlem/ContentView.swift, Mlem/Custom Tab Bar/FancyTabBar.swift, Mlem/Custom Tab Bar/FancyTabBarLabel.swift, Mlem/Models/Saved Account.swift, Mlem/Models/Trackers/Saved Account Tracker.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Add Account View.swift, Mlem/Views/Tabs/Profile/Profile View.swift, Mlem/Views/Tabs/Profile/User View.swift, Mlem/Views/Tabs/Settings/Settings View.swift, Mlem/Window.swift
- Ongoing accessibility improvements
- Sets up #32 
This PR reworks the account switching/account adding interface and improves accessibility on the tab bar:
- Popup is now a modal, not a ContextMenu on the Profile tab. It can be accessed either by swiping up on the tab bar or by long pressing the Profile tab
- When accessibility font sizes are detected, the long press on Profile tab gesture is disabled to allow the tab HUD to properly function; the swipe up remains active
- Login and account switching are now part of the same sheet
- Accounts are now grouped by instance
- "Switch account" has been moved from Settings to the Profile tab
- The nav bar now displays normally in the Profile tab
https://github.com/mlemgroup/mlem/assets/44140166/fa340200-6e9f-4438-92b0-e32779e956e4 …
=> Tab bar 2: accessible boogaloo (now with bonus scope creep!)

Mlem/Views/Shared/TokenRefreshView.swift
- no issue raised, just spotted it while doing some testing on error handling
The recent changes to the token refresh modal have left the initial state set to `.success` instead of `.initial`, this means when the modal is presented it is displaying that login was successful and the field/controls are disabled leaving the user stuck inside the modal and unable to continue.
=> fix - initial state of token refresh modal

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/Environment - Force Onboard.swift, Mlem/Models/Saved Account.swift, Mlem/Models/Trackers/Saved Account Tracker.swift, Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift, Mlem/Window.swift
Little PR to fix up some logic around the account switcher. Deleting the active account is now possible; if another account is available it swaps you to it, otherwise it chucks you out to the onboarding flow.
Added an environment function to force into the onboarding flow.
=> added duplicate avoidance, logic for deleting the last account

Mlem.xcodeproj/project.pbxproj, Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/API/Requests/Post/EditPost.swift, Mlem/Logic/Participating/Edit Post.swift, Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Composer/PostDetailEditorView.swift
Backend prep for the editing posts feature. No functionality is changed in this PR. I would have done more, but I'll be going away for a week so I thought I'd submit what I've done so far - if someone else wants to finish this feature, have at it.
I've separated the editing interface from `PostComposerView` into a separate `PostDetailEditorView`. I imagine this new `PostDetailEditorView` could be used in a `PostEditorView` sheet similar to `PostComposerView` but for editing the post. I've also implemented the `editPost` function to perform the post edit. 
Related: #36, #134
=> Edit Post Prep

Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
-
This PR fixes an issue where images were tappable outside of their frame. Nuke images apparently refuse to respect frame, so I've disabled hit testing on the image itself and added an overlay to register hits which can be bounded to an optional `maxHeight` parameter.
=> fixed LazyImage clipping

Mlem/Logic/Participating/Edit Post.swift, Mlem/Models/Composers/PostEditor.swift, Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift
Expanded posts weren't updating when the body of the post was updated. Since they aren't handled with the post tracker, this required some slight jank--PostEditor now has an optional callback that takes in the updated post. This gets used to update the state back in `ExpandedPost` when the edit call completes.
https://github.com/mlemgroup/mlem/assets/44140166/9fe9a552-33a6-4b7c-96b9-f0d3b9e5ede5
=> Fixed expanded post not updating when edited

Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Components/Thumbnail Image View.swift, Mlem/Views/Shared/Components/ThumbnailImage.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Headline Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift, Mlem/Views/Shared/Posts/Post Sizes/UltraCompactPost.swift
- closes #279 
- closes #281 
This PR allows tapping thumbnails in feed to open the post content. It moves the duplicated thumbnail code from `HeadlinePost` and `UltraCompactPost` into a common `ThumbnailImage`, which now uses `CachedImage` in place of `CachedAsyncImage`, which enables tapping thumbnails to open QuickLook
The "error loading image" graphic has also been replaced with a much gentler one.
https://github.com/mlemgroup/mlem/assets/44140166/5d140747-86d0-4962-93f9-f45fe888d536
=> Tap Thumbnails to Expand

Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift, Mlem/Views/Shared/Posts/Components/Post Header.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Shared/Posts/Post Sizes/UltraCompactPost.swift
- closes #373 
This PR adds the NSFW blur to the community and user avatars, plus adds post context to a lot of the user avatar labels so they can accurately detect NSFW posts.
The NSFW filter will not be appropriately applied to the user avatar if the community is NSFW but the post is not; this should be fixed implicitly when we migrate to a middleware post model that will be automatically flagged NSFW if its community is.
This PR also makes the instance text not tappable, as per Slack discussion
https://github.com/mlemgroup/mlem/assets/44140166/982b5336-48ce-4acd-95aa-66a0068b3e1f
=> applied nsfw filter to community avatar

Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Models/ImageSize.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Components/Thumbnail Image View.swift
Follow-up PR to #408 
This PR introduces an image size cache that exists independently of the Nuke cache--it can hold way more items because it only cares about the URL and the size of the image associated with it. This avoids unnecessarily squishing images into squares because they didn't happen to get prefetched in time.
=> Improved Smooth Scrolling

Mlem.xcodeproj/project.pbxproj, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Components/Thumbnail Image View.swift, Mlem/Views/Tabs/Feeds/Feed View Logic.swift
- closes #419 
This PR makes thumbnails in compact and headline mode behave properly:
- Tapping an image thumbnail opens the image viewer and marks the post as read
- Tapping a link thumbnail opens the link and marks the post as read
Updating post state unfortunately closes the QuickLook viewer, so image posts have to send the read call on dismissal of the viewer. I've added an optional `dismissCallback` parameter to `CachedImage` to achieve this.
**IMAGE POST**
https://github.com/mlemgroup/mlem/assets/44140166/08ac5a0d-a93b-4328-aea2-08719c366d87
**LINK POST**
https://github.com/mlemgroup/mlem/assets/44140166/5077a850-35ef-4fd6-97b3-3850fa01c567
=> Thumbnail refinements

Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/API/Models/APIErrorResponse.swift, Mlem/Views/Shared/Accounts/Add Account View.swift
Closes #83
Currently, when adding a new account, the user much enter an instance url in the form `lemmy.world`. This PR makes the instance field accept other forms of URL too.
Test cases:
```
lemmy.world
www.lemmy.world
https://lemmy.world/
https://www.lemmy.world/
lemmy.world.
lemmy.world/
lemmy.world/post
https://lemmy.world/post
```
=> Make instance field more lenient

Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Comments/Components/CommentBodyView.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/Feed Post.swift
- #442
This PR fixes the "Show instance" toggles for users and communities in posts and comments.  Comments were inverted (off showed the instance, on hid the instance) and posts always would show the instance regardless of setting.
This PR also fixes a bug where every post author in the feed was being rendered as OP (orange). This was because we were including the post context when rendering the label when we shouldn't've been.
n/a
n/a
=> Fixed show instance toggles for posts and comments (fixes #442)

Mlem/Custom Tab Bar/FancyTabBar.swift
- #440
This PR does not address the entire bug, but one half of it.  It updates the VO for the navigation tabs to include the label in them.  ("Selected (if selected), Feeds, Tab 1 of 5" instead of just "Tab 1 of 5").
n/a
Perhaps we should split the bug into two separate items.
=> Fixed navigation tab VO text (partial fix for #440)

Mlem/Views/Shared/Markdown View.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
Not sure what you'd like the process to be for this one, but since I couldn't find the task in the backlog I'll just ask you here. Let me know if you'd like this to go another way, or if you want to postpone this until later on.
- #437
This deemphasises the body in large posts by simply making it 50% opaque.
I'm not sure if that's the correct approach, it's certainly a very simple solution. I'm assuming that links should stay clickable, so the alternative approach I can think of is adding a new theme for the `MarkdownView`. That would set all the colors explicitly which is probably better, but would also introduce some more code to maintain. I can give that one a go if you'd prefer it (or any other if you have a suggestion).
=> Deemphasize body in feed of large posts

Mlem.xcodeproj/project.pbxproj, Mlem/Views/Shared/Components/Buttons/Save.swift, Mlem/Views/Shared/Components/Buttons/Vote Complex/Vote Complex.swift, Mlem/Views/Shared/Components/Interaction Bars/InfoStack.swift
Attaches proper accessibility tags to the items in the InfoStack.
Also removed the "votes" label from the vote complex--that item only ever exists in an InfoStack, which by default has the vote count in it, so the total votes were being read twice. This way also respects "show downvotes separately" for free.
=> Fixed accessibility on infostack

Mlem/Enums/FeedType.swift, Mlem/Enums/Settings/CommentSortType.swift, Mlem/Enums/Settings/PostSortType.swift, Mlem/Enums/Settings/Vote Complex Style.swift, Mlem/Views/Shared/Components/Buttons/Vote Complex/Standard Vote Complex.swift, Mlem/Views/Shared/Components/Buttons/Vote Complex/Vote Complex.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Tabs/Feeds/Components/PostSortMenu.swift, Mlem/Views/Tabs/Settings/Components/Settings Item.swift, Mlem/Views/Tabs/Settings/Components/Views/Accessibility/AccessibilitySettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Comment/CommentSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Community/CommunitySettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/TabBar/TabBarSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/User/UserSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Filters/FiltersSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
- closes #411 
- closes #248 
This PR tidies up settings:
- "Vote complex style" has been renamed to the more intuitive "Vote buttons"
- "Standard" vote complex has been renamed "classic" to reflect that it is no longer the default
- All labels have been capitalized and all section footers now all have periods. Tightened up the wording, improved consistency, and removed unnecessary information.
- All relevant settings now use either `SwitchableSettingsItem` or `SelectableSettingsItem`
- `SwitchableSettingsItem`'s `settingPictureColor` parameter now has a default value of `.pink`; redundant arguments have been removed.
=> Settings Improvements

Mlem.xcodeproj/project.pbxproj, Mlem/App State.swift, Mlem/ContentView.swift, Mlem/Enums/Settings/ProfileTabLabel.swift, Mlem/Haptics/Haptic Manager.swift, Mlem/Models/Saved Account.swift, Mlem/Models/Trackers/Saved Account Tracker.swift, Mlem/Repositories/PersistenceRepository.swift, Mlem/Views/Shared/TokenRefreshView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/TabBar/TabBarSettingsView.swift
- closes #289 
This PR adds the ability to create and save profile nicknames, and use those nicknames in the profile tab.
It also removes the old `showUsernameInNavigationBar` toggle in favor of a new 4-way selector: username, instance, nickname, or anonymous.
https://github.com/mlemgroup/mlem/assets/44140166/255c64ce-d195-4823-8cf5-6cf677bcaaf9
=> Profile Nicknames

Mlem/Views/Shared/Posts/Post Sizes/UltraCompactPost.swift
- closes #468 
Post context was wrongly being passed to the user label in UltraCompactPost, causing all users to be flaired as OP.
Fixed:
=> Fixed an issue where all posts in a community showed the poster as OP

CONTRIBUTING.md, Mlem/Views/Tabs/Settings/Components/Views/About/AboutView.swift, README.md
- Fixes #415
This PR changes the default URL to a new one with fresh cache, to allow people to join the right space, if the old one was cached wrongly
I've added an extra local alias to the space so that this one directs the correct way
=> Change link from #mlemapp to #mlemappspace

Mlem/Views/Tabs/Search/Search View.swift
Disables autocorrect for the community search
I don't think it makes sense to autocorrect text that clearly won't be sentences or words. It happened multiple times that I typed something correctly and it got "corrected" to something entirely different
=> Removed autocorrect/-capitalisation from search

Mlem/Views/Tabs/Inbox/Inbox View.swift
- #445 
Using user defaults to persist the `shouldFilterRead` toggle for the inbox
=> Persisting inbox read/unread filter (#445)

Mlem/ContentView.swift, Mlem/Views/Shared/Composer/PostDetailEditorView.swift, Mlem/Views/Shared/Composer/ResponseEditorView.swift
- #474 
Fixes the cursor jumping to the end once when starting to edit a commend/post
It moves the `NavigationStack` from both the `ResponseEditorView` and `PostEditorView` into a parent view
The state seems to be fine and I couldn't quite figure out what was going on. It's especially odd since it's only happening once and not for everyone. I started poking around and messing with some things. Moving the `NavigatioStack` out of the editing views seems to have fixed it. I'll keep testing this on my device for some time to see if the issue pops up again and leave this PR as a draft until I'm reasonably certain it's gone for good.
@EricBAndrews assuming it stays fixed and doesn't reappear, would this be an acceptable solution?
=> Fixed cursor jumping to the end when editing a post/comment (#474)

Mlem/Views/Shared/Markdown View.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
- #361
This addresses a few of the markdown issues inside the feed (large post size). It's far from being a proper solution for the markdown situation, but it's a small fix that avoids many of the larger issues in the meantime.
- Uses a markdown theme with minimal styling to avoid some of the current issues where the entire post takes on the same styling that the first element in the body has (e.g. everything is a heading, quoted post, ...)
- Also fixes text not being truncated at all in the feed
| Previous | New |
|---|---|
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 21 26 27](https://github.com/mlemgroup/mlem/assets/20093825/4812d34e-7186-4596-ab2f-3baa63cf6f46)  |  ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 21 27 …
=> Small improvements to markdown in feed (large post size)

Mlem/Custom Tab Bar/FancyTabBar.swift, Mlem/Custom Tab Bar/FancyTabBarLabel.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Components/Thumbnail Image View.swift, Mlem/Views/Shared/Links/Community Link View.swift, Mlem/Views/Shared/Links/User Profile Label.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar Header Avatar.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar Header.swift
- 🧹 housekeeping
This PR makes some minor housekeeping/polishing tweaks:
- CachedImage now accepts a `contentMode` parameter to determine how the image should be resized. By default this is `.fit`, which causes tall images to get shrunk down to fit the maxHeight instead of being clipped; for avatars and such, it has been overridden to `fill`.
- Gave the flair icon the font size of `.footnote` so it's a little less overwhelmingly large
- Used the previously uncalled `postBodyText` function in `LargePost` to re-enable truncating large posts in feed
- Temporarily disabled the "maximize" icon in minimized posts so we can see how it feels without it on the nightly
Simulator doesn't seem to indicate any regression on scrolling performance.
=> Minor Polishing

Mlem.xcodeproj/project.pbxproj
XCode cloud is rejecting our nightly because 1.0.1 is released. This should fix that.
=> Bumped version to 1.0.2

Mlem/App Constants.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
- #480
Removes limiting the height of images in the feed (large post size).
| Currently | New |
|---|---|
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 08 50](https://github.com/mlemgroup/mlem/assets/20093825/f68dfaee-3e91-4c7f-a334-8ce982c8e09a) | ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 10 36](https://github.com/mlemgroup/mlem/assets/20093825/f4769219-4c0e-4fef-9044-b37673e6926d) |
There are two variants of how to expand the image:
| Masked with padding | full width |
|---|---|
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 10 02](https://github.com/mlemgroup/mlem/assets/20093825/592b7856-e082-46a9-b1d8-92a0c0f272f2) | ![Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 10 49](https://github.com/mlemgroup/mlem/assets/20093825/c5fe3d79-8bf …
=> Expand images in feed (large post size)

Mlem/Extensions/View - NavigationBar Color.swift, Mlem/Views/Tabs/Feeds/Feed View.swift
- #365 
Workaround for issue #365:
- Navigation bar now remains visible on device rotation.
- Navigation bar background visibility in "Feed" tab has been changed from `.automatic` to `.visible` (i.e. separator line between nav bar and content is always visible).
- Navigation bar background behaviour is unchanged in all other tabs.
| Before  | After |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 01 43 07](https://github.com/mlemgroup/mlem/assets/2549615/9936d530-5c93-47da-aff9-811383e97237) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-16 at 01 42 52](https://github.com/mlemgroup/mlem/assets/2549615/a7b3ee7c-06a3-4b4c-b085-7e14bee3a192) |
=> Fix issue where navigation bar background may disappear on device rotation

Mlem/Enums/Settings/CommentSortType.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift
- #528
Fixes issue described here #528
- Fix involves directly setting the local value for comment sorting from UserDefaults on init.
- Remove AppStorage var that was never mutated.
- Local comment sorting value overrides Settings value, so we now use the local value in Expanded Post logic.
- Made `commentSortingType` not private for now, so it can be used in Expanded Post logic (unfortunate).
After Fix:
https://github.com/mlemgroup/mlem/assets/2549615/d202ad8e-6448-473a-90f5-a6f2073a5cd9
Remembers locally picked sort type after change in Settings:
https://github.com/mlemgroup/mlem/assets/2549615/b475ccac-688d-43e3-9df0-dbfda65b9694
=> - Fix issue #528

Mlem/Custom Tab Bar/FancyTabBar.swift, Mlem/Enums/TabSelection.swift
- Related to #457
When scrolls a scroll view, and then triggers a programmatic "scroll-to" event via `FancyTabBar`, the previous implementation caused programmatic scrolling to not reliably work.
- Note this bug only affects programmatic scrolling while scroll view is actively scrolling/animating scrolling.
Previously, implementation used `DispatchQueue.asyncAfter` to trigger "tab re-selected" event:
- My guess is this method caused any UI logic that relied on state changes performed inside that `asyncAfter` block to "escape" SwiftUI's rendering loop and/or execution context (possibly related to RunLoop in tracking mode).
- This was causing programmatic scrolling to at times fail when scroll view is still animating scrolling.
- Programmatic scrolling would always work when scroll view is …
=> Fix tab reselect logic causing programmatic scrolling to not reliably work

Mlem.xcodeproj/project.pbxproj, Mlem/Error Handling/ErrorHandler.swift, Mlem/Logic/Networking/InternetConnectionManager.swift, Mlem/Notifications/NotificationDisplayer.swift, Mlem/Notifications/NotificationMessage.swift, Mlem/Views/Shared/Error View.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Tabs/Profile/User View.swift, Mlem/Views/Tabs/Profile/UserFeedView.swift, Mlem/Views/Tabs/Settings/Components/Views/Advanced/AdvancedSettingsView.swift
I've made some changes to the way errors are handled in the `ExpandedPostView` and `UserView`. I've also refactored `UserView` quite a bit.
Error changes:
If the error handler is told to show an alert, and the internet is offline, it will show a simple "You're offline" toast instead of a full error message. 
<br/>  
<br/>  
If the user loads a comments page, and an error is thrown, the error message will be shown inline instead of as an alert. This makes it less intrusive. If the error was caused by the user being offline, the page will attempt to reconnect every second. If the internet comes back online, it will load the comments automatically. 
<br/> 
<br/>  
<br/>
<br/> 
If the error was _not_ caused by the internet being offline, it'll instead show "Something went wrong" with a "Try …
=> Error handling

Mlem/Views/Shared/Cached Image.swift
- Don't see an open issue, but various reports on L/mlemapp, etc.
Fixes issue where CachedImage may overflow its expected size:
- Caused image to be partially cut off.
- Caused parent layout to break in some situations.
The following isn't required to fix this issue, but it seemed reasonable to specify `contentMode` when resizing the image:
```
.processors([
.resize(
size: size,
contentMode: contentMode == .fill ? .aspectFill : .aspectFit)
])
```
| After  | Before |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 13 mini - 2023-08-26 at 16 53 29](https://github.com/mlemgroup/mlem/assets/2549615/28f1d2de-15a2-464a-b6d6-fefb449bf354)  | ![Simulator Screenshot - iPhone 13 mini - 2023-08-26 at 16 52 27](https://github.com/mlemgroup/mlem/assets/2549615/01c99ea8-d5cf-4871-887 …
=> Fix issue where cached image may cause parent view layout to break

Mlem.xcodeproj/project.pbxproj, Mlem/App Constants.swift, Mlem/Extensions/Array+SafeIndexing.swift, Mlem/Extensions/Swipey Actions.swift, Mlem/Views/Shared/Comments/Comment Item Logic.swift, Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Tabs/Inbox/Feed/Mentions Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Messages Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Replies Feed View.swift
- #473
1. Adds a trailing swipe action to expand/collapse comments (`CommentItem`).
2. Refactors SwipeyView to support multiple leading/trailing actions along with predefined swipe drag action thresholds.
- This should help us get closer to allowing users customize swipe actions like in Apollo.
https://github.com/mlemgroup/mlem/assets/2549615/75971a4a-2bd2-4df6-b093-3243f9268d50
=> Swipe to expand/collapse comments + refactor swipe actions

Mlem/Views/Shared/Components/InteractionBarView.swift
Two small changes to how the interaction bar works:
- Widgets are now assigned id based on offset (prevents id conflicts with multi-widgets)
- InfoStack now bleeds behind widgets if out of space
=> made info stack less broken with many widgets

Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift
- nope lol
This PR fixes the widget wizard not setting collection rect properly in the view modifier. It replaces that logic with a fun little `.overlay`/`GeometryReader` hack.
=> fixed the widget wizard for ios 17

Mlem/Views/Shared/Error View.swift
Follow-up from #562. If Lemmy returns a basic text (not json) error, clicking the "Show details" button on the `ErrorView` will let you see the error text that was returned by the API. Previously, it would only show "Json decode error".
=> Make ErrorView show non-json errors if they occur

.github/workflows/ci_build.yml, .github/workflows/ci_lint.yml, Mlem.xcodeproj/xcshareddata/xcschemes/Mlem.xcscheme
- No issues for this
This PR adds two new GitHub Action jobs:
- One that builds with `xcodebuild`
- One that tests with `xcodebuild`
It also disabled the UI tests project from running as it sounds like that is a waste of time and a stubbed out empty project.
n/a
This PR hard codes a specific device to build and test on in the iOS simulator (iPhone 14) as well as an iOS version string.
These will change over time when GitHub updates their MacOS agents but I added a step which prints available combinations so updating will be easy.  These values should be pretty stable (months between changing, not weeks) but we could probably automate the selection somehow with some fancy grep.
=> Add GitHub action CI builds

Mlem/Views/Tabs/Feeds/Components/Sidebar Header Avatar.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar Header Label.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar Header.swift, Mlem/Views/Tabs/Profile/User View.swift
- n/a
- Updates default avatar to be `person.fill` instead of a grey circle.
- Updates the labels in header to be `.primary` color instead of `.white` as that was basically unreadable if you had no banner or a light colored banner.
- Added more previews and fixed one with a crash at preview time.
n/a
=> Update profile headers to be more readable

Mlem/Views/Tabs/Feeds/Components/Sidebar Header.swift
- n/a
Wide banners are causing profile/community sidebar views to go off into the sunset.  This attempts to fix that with framing.
Before:
After:
Not exactly sure of the nuances of `CachedImage`.  This seems to fix it but the params passed into `CachedImage` seem like they would already be restricting it.
=> Fixed wide banners from derailing whole header

Mlem/App Constants.swift, Mlem/Views/Tabs/Settings/Components/Settings Item.swift, Mlem/Views/Tabs/Settings/Components/Views/Accessibility/AccessibilitySettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Comment/CommentSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Community/CommunitySettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/User/UserSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Filters/FiltersSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
- closes #596
This PR fixes a regression where settings did all feature icons--a feature that is important to enable our dyslexic users to navigate the hefty stack of settings we offer.
It also introduces an option to disable settings icons and removes some unnecessary descriptive text.
=> Fixed settings icon regression

Mlem/Extensions/NSFW Overlay.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
- TF feedback
https://github.com/mlemgroup/mlem/assets/44140166/2b7e9982-7664-4014-af22-c7eb53080239
This PR subtly adjusts the behavior of the NSFW filter:
- In feed: behavior unchanged. Tapping the exclamation mark reveals the image; tapping anywhere else navigates to the expanded view
- In expanded view: tapping anywhere on the image reveals the image
To support this, I have added a default-false `tapAnywhereToReveal` bool to the NSFW filter to enable this behavior.
=> Tweaked NSFW Filter Behavior

Mlem/Views/Shared/Links/Community/CommunityLinkView.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift, Mlem/Views/Shared/Website Icon Complex.swift
- Slack
This PR applies a band-aid fix to scrolling performance by locking all images into a square and all web complexes into a rectangle.
It also updates CommunityLinkView to use the new navigation enum type.
=> Hacked images to be smooth for TF release

Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift, Mlem/Views/Shared/Website Icon Complex.swift
- Resolves issue #630
- Fixes `LargePost` layout for `.link` post type getting cut off in landscape mode on iPad (especially when sidebar is open).
Before Fix (latest `/dev` build)
After Fix (iPad)
https://github.com/mlemgroup/mlem/assets/2549615/496d7e22-0984-48dc-813b-d68adc61e516
After Fix (iPhone)
https://github.com/mlemgroup/mlem/assets/2549615/e77e459e-6048-4947-8df7-b7f9cb23d344 
- Tested on iOS 16.4 simulator, iOS 17 simulator, iPhone 13 mini (iOS 17 RC).
=> Fix large post link type layout

Mlem.xcodeproj/project.pbxproj, Mlem/ContentView.swift, Mlem/Extensions/PresentationBackgroundInteraction.swift, Mlem/Views/Shared/Composer/PostComposerView.swift, Mlem/Views/Shared/Composer/ResponseEditorView.swift
- #602 
- User feedback: Want to read what they're responding to while create/editing.
This PR includes two UI changes to Post editor and Response editor when presented as sheets:
1. Adds `.medium` presentation detent, while allowing users to interact with the view behind it while in `.medium` detent.
- Note: Interaction with view behind is only available on iOS 16.4 or later.
2. Disable interactive dismissal when editor has content.
Sheet initially presents at `.medium` detent before moving to `.large` on initial presentation:
- To immediately present sheet in `.large`, we should pass a `selection` binding to `.presentationDetents(...)`, but doing so causes the content view to call into its body, resulting in visible lag when switching between detents.  
- To workaround this animation …
=> Editor sheet detents

Mlem/App Constants.swift, Mlem/Extensions/AlternativeIconCell.swift, Mlem/Views/Tabs/Settings/Components/Settings Item.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/AppearanceSettingsView.swift
- #641 
This PR fixes settings icons displaying as too large on iOS 17. It also adds a very light border to the app icon settings item so that icons with white backgrounds (i.e., Classic Lemmy) have delineated borders.
=> Fixed settings icon sizing issues

Mlem/Views/Shared/Comments/Comment Item.swift
Fixed an issue where comments would have a transparent background in the context menu.
| Before  | After |
| ------------- | ------------- |
| <img width="376" alt="Screenshot 2023-09-24 at 16 27 36" src="https://github.com/mlemgroup/mlem/assets/78750526/a07cbf0d-8c20-410e-824b-c6dfe73a665b">  | <img width="382" alt="Screenshot 2023-09-24 at 16 27 58" src="https://github.com/mlemgroup/mlem/assets/78750526/2cb34b66-2692-43dc-b418-c23519d36329">  |
=> Comment background color fix

Mlem.xcodeproj/project.pbxproj, Mlem/Icons.swift, Mlem/Models/Content/Post Model.swift, Mlem/Views/Shared/Accounts/Accounts Page.swift, Mlem/Views/Shared/Comments/Comment Item Logic.swift, Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Comments/Components/CommentBodyView.swift, Mlem/Views/Shared/Components/Components/InfoStackView.swift, Mlem/Views/Shared/Components/InteractionBarView.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Compact Post.swift, Mlem/Views/Shared/PublishedTimestampView.swift, Mlem/Views/Shared/UpdatedTimestampView.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Mention View.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Message View.swift, Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Reply View.swift
- closes #156 
This PR changes posts and comments to display updated time instead of published if the item has been edited:
=> Added updated time display

Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
This PR addresses a scrolling regression where scrolling back up the feed was choppy.
=> Fixed scrolling regression

Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/Models/Trackers/Post Tracker.swift
Fixes crash (debug builds)/error with haptics (production) described here: #635 
- Opening a post via a link triggers link resolver logic.
- Link resolver returns post object.
- Navigation maps post to the correct view, but doesn't add it to its environment's `PostTracker`.
Also, made `PostTracker.items` private(set) so external users don't mutate state in unexpected ways (nothing was doing this, but just to be safe).
I kept it to a simple fix, but at first it was unclear that you have to explicitly call `add(...)` even if you pass `initialItems` on init.
- Probably makes more sense to add `initialItems` on init to reduce awkwardness at call site when we touch `PostTracker` again?
=> Fix crash when post object originates from link resolver

Mlem/Extensions/Swipey Actions.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Tabs/Inbox/Feed/Mentions Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Messages Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Replies Feed View.swift
- closes #621 
This PR addresses swipey actions and context menus conflicting. Previously, an aborted context menu pop that triggered the animation would invoke the drag handler of the swipey action, leading to the swipey action either jumping to the drag state or, worse, duplicating the view and showing them one atop the other. All .contextMenu view modifiers have been moved to occur *after* swipey action view modifiers, ensuring that the context menu takes priority.
=> Fixed swipey action bad behavior with context menus

Mlem/API/Models/APIErrorResponse.swift, Mlem/Views/Shared/Accounts/Add Account View.swift
Before, if you tried to login to a private instance you'd get a generic 'file a bug report' message. Now you'll see 'instance is private' instead. 
This is very unlikely to happen to anybody. I ran into this whilst setting up a local instance
=> Show error when instance is private

Mlem/API/APIClient/APIClient.swift, Mlem/Models/Saved Account.swift, Mlem/Models/Trackers/RecentSearchesTracker.swift, Mlem/Repositories/PersistenceRepository.swift, Mlem/Views/Tabs/Search/RecentSearchesView.swift, Mlem/Views/Tabs/Search/SearchResultListView.swift, Mlem/Views/Tabs/Search/SearchView.swift, MlemTests/Model/LemmyURLTests.swift, MlemTests/Persistence/PersistenceRepositoryTests.swift
- Slack
Changed how recent searches are handled persist them per-account. This involves:
- Changing `loadRecentSearches` to `reloadRecentSearches`, which will clear the value and reload using the current account hash (it's only called in one place on `.onAppear`, so this shouldn't break anything)
- Persisting recent searches as a map of `accountHash` to list of `ContentModelIdentifier`
https://github.com/mlemgroup/mlem/assets/44140166/15b750b9-0237-4986-94cd-6dbb2ccadf60
=> Made recent searches be stored per-account

Mlem.xcodeproj/project.pbxproj, Mlem/Enums/AvatarType.swift, Mlem/Views/Shared/Avatars/DefaultAvatar.swift, Mlem/Views/Shared/Avatars/DefaultAvatarView.swift, Mlem/Views/Shared/Links/AvatarView.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar Header Avatar.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar Header.swift, Mlem/Views/Tabs/Feeds/Components/Sidebar View.swift, Mlem/Views/Tabs/Profile/User View.swift
- closes #688 
This PR fixes two problems relating to sidebar avatars, described in #688. It also takes the opportunity to rename `CommunitySidebarHeaderAvatar` to `SidebarHeaderAvatar`, since it is used for both, and increase code reuse around default avatars (extracted `AvatarType` to be a regular enum conforming to `AssociatedIcon`, and created a `DefaultAvatarView` to unify handling fallback avatars.
**Current** | **Incoming**
---|---
=> Fixed default sidebar avatars

Mlem/Models/Trackers/RecentSearchesTracker.swift
This PR addresses navigation back to the new search view being extremely choppy due to `reloadRecentSearches` triggering a view redraw for every single search. They are now accumulated into a temporary array and updated all at once.
=> Optimized search view rendering

Mlem/ContentView.swift, Mlem/Icons.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/TabBar/TabBarSettingsView.swift
Allows the user to turn off the tab bar swipe-up gesture, which accesses the account switcher. Someone on mlemapp requested this
=> Allow disabling swipe-up for account switcher

Mlem/API/Internal/HierarchicalComment.swift, Mlem/Enums/Content Type.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Models/Trackers/RecentSearchesTracker.swift, Mlem/Repositories/PersonRepository.swift, Mlem/Views/Tabs/Profile/User View.swift, Mlem/Views/Tabs/Profile/UserFeedView.swift
- closes #686 
- closes #327 
This PR fixes two problems with the profile:
1. Refreshing own profile always throws an error. This was caused by the refresh function opportunistically trying to update the app state with the new profile information, which was in turn causing a view rerender and therefore cancelling the saved items load task. I have moved that logic to happen after saved items are loaded and added a comment re: long-term opportunistic profile refresh
2. Upvote counts don't update when refreshing. This was caused by the profile simply trying to *add* the new (refreshed) items to the trackers, which led to them all being rejected because they were dupes. I changed the behavior to *reset* the trackers instead, which is fine because we never perform any load action other than …
=> Fixed profile refresh problems

Mlem/Views/Tabs/Inbox/Inbox View Logic.swift
- closes #696 
This PR fixes a bug where interacting with inbox items would increment the inbox unread counter.
It introduces a guard on the markMentionRead and markReplyRead to no-op if the call would have no effect.
=> Fixed inbox unread counter bug

Mlem/Views/Tabs/Search/SearchResultsView.swift
Got a rate limit whilst searching. This PR reduces the number of API requests we make by refreshing the search results less often.
Search was refreshed every time the search field content is changed (ie, when the user types another letter)
Search is refreshed if the user stops typing for 0.2 seconds (thoughts on this delay? I type faster than 0.2 seconds per key so it works for me, but this may not be true for everyone)
=> Avoid search rate limit

Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift
Adds a small reset button to the widget wizard that resets the widgets back to the default layout
Related to this post https://sh.itjust.works/post/7366384
=> Widget Wizard "Reset" button

Mlem.xcodeproj/project.pbxproj, Mlem/Error Handling/ErrorHandler.swift, Mlem/Icons.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Views/Shared/Loading View.swift, Mlem/Views/Tabs/Feeds/Components/NoPostsView.swift, Mlem/Views/Tabs/Feeds/Feed View Logic.swift, Mlem/Views/Tabs/Feeds/Feed View.swift
Centered the loading graphic and replace "no posts to be found" message (see images).
<p float="left">
</p>
<p float="left">
</p>
=> Better 'no posts to be found' message

Mlem/Views/Tabs/Feeds/Feed View.swift
- closes #750 
This PR fixes the community reloading when navigating back from a post. It introduces a state variable to track whether the site information has loaded. Posts are now not displayed until site information has loaded to avoid a jarring redraw if the sort type is updated, and the sort type uses this variable to ensure it only updates the sort information the first time site information loads.
=> fixed sort resetting when navigating back from a post

Mlem/API/APIClient/APIClient+Post.swift, Mlem/API/Models/Posts/APIPostAggregates.swift, Mlem/API/Models/Posts/APIPostView.swift, Mlem/API/Requests/Post/GetPosts.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Repositories/PostRepository.swift, Mlem/Views/Shared/Links/User/UserLabelView.swift, Mlem/Views/Tabs/Feeds/Feed View Logic.swift, Mlem/Views/Tabs/Profile/User View.swift
- closes #758 
- closes #674 
This PR enables 0.19 compatibility for posts:
- Adds cursor pagination (based on @mormaer's cursor pagination branch)
- Updates some models for 0.19 compatibility:
- `APIPostAggregates` now lists fields not present in 0.19 as optional
- `APIPostView` now has an optional `creatorIsModerator` field
=> 0.19 Post Compatibility

Mlem.xcodeproj/project.pbxproj, Mlem/ContentView.swift, Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/Models/QuickLookState.swift, Mlem/Views/Shared/Cached Image.swift, Mlem/Views/Shared/Components/Thumbnail Image View.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
- #747 (reported via Lemmy community)
1. Fixes issue where rotating device while QuickLookUI is presented causes that UI to be dismissed.
2. Adds a progress view overlay on top of CachedImage while QuickLookUI is preparing to open, since sometimes QuickLookUI doesn't immediately open on tap gesture.
https://github.com/mlemgroup/mlem/assets/2549615/31b792ff-7480-4df8-82c3-f61818a5e0e0
Rotation bug **might** not be reproducible in iOS simulator.
=> Fix quicklook dismiss on rotate

Mlem/Models/User-Interactable/Menu Function.swift, Mlem/Temp Image Viewer/ZoomableImageView.swift, Mlem/Views/Shared/Components/Components/Menu Button.swift
Fixes a bug with the new image viewer where it would share the image URL instead of the image itself. To support this, adds a `.shareImage` case to `MenuFunction`.
=> made image share share image directly instead of url

Mlem/Enums/Settings/PostSortType.swift, Mlem/Views/Tabs/Feeds/Feed View.swift
Seems like I got the wrong name for the top 3/6/9 month sort modes last time. It annoys me that it isn't consistent haha
=> Fix top 3/6/9 month sort modes

Mlem/Views/Tabs/Inbox/Feed/AllItemsFeedView.swift, Mlem/Views/Tabs/Inbox/Feed/Mentions Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Messages Feed View.swift, Mlem/Views/Tabs/Inbox/Feed/Replies Feed View.swift, Mlem/Views/Tabs/Inbox/Inbox View.swift, Mlem/Views/Tabs/Profile/Profile View.swift, Mlem/Views/Tabs/Profile/User View.swift, Mlem/Views/Tabs/Search/SearchView.swift
- sry
This PR adds the reselect scroll-to-top to the inbox and the profile view.
I took a couple hacks at search, but programmatically selecting that search bar turns out to be deeply tricky
=> Added reselect actions to inbox and profile

Mlem.xcodeproj/project.pbxproj, Mlem/API/APIClient/APIClient+Post.swift, Mlem/API/Models/Common/SuccessResponse.swift, Mlem/API/Requests/Post/MarkPostRead.swift, Mlem/Models/Content/Post Model.swift, Mlem/Models/Trackers/Post Tracker.swift, Mlem/Repositories/PostRepository.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Shared/Posts/Feed Post.swift
- #783 
This PR includes two small bugfixes:
- Fixed being unable to block users from posts following the migration to `PostModel`. `.id` (hash of the struct) was being passed in instead of `.userId` (Lemmy-side user id), resulting in a 404.
- Fixed marking posts as read not working on 0.19. Added decoding for the new SuccessResponse, and some compatibility logic to handle multiple API versions.
=> 1.1.1 Bugfixes

Mlem/API/Models/APIErrorResponse.swift, Mlem/ContentView.swift, Mlem/Error Handling/ErrorHandler.swift, Mlem/Notifications/NotificationDisplayer.swift, Mlem/Views/Shared/Accounts/Add Account View.swift, Mlem/Views/Shared/TokenRefreshView.swift
- Slack
This PR adds some logic to prompt users to reauthenticate if their saved credentials are invalid, namely:
- `invalidSession` errors are now thrown for any credential failure response
- `AddSavedInstanceView` now catches those as login failures instead of manually checking for `.isIncorrectLogin` on a response error
- The expired session notification sheet is now attached normally to `ContentView` instead of being programmatically presented through the `NotificationDisplayer`
- The expired session notification sheet now resets the `invalidSession` flag on the `ErrorHandler` when dismissed, which prevents an invalid session message being erroneously displayed when cancelling the token refresh and switching accounts
To simulate the use case of users attempting to use accounts saved …
=> 0.19 account reauth

Mlem/Logic/Abbreviate Numbers.swift, Mlem/Models/Content/Inbox/MentionModel.swift, Mlem/Models/Content/Inbox/ReplyModel.swift, Mlem/Views/Shared/Posts/ExpandedPostLogic.swift, Mlem/Views/Shared/Posts/Feed Post.swift
- Made a few context menu actions that weren't in Title Case conform to Title Case
- Added a destructive confirmation to the "Block Community" context menu action on posts (closes #284)
- Fixed a bug where the number of comments that a user has was displayed incorrectly in search if they had >1M comments
=> Label Tweaks

Mlem/Views/Shared/Links/User/UserLabelView.swift
Tweaked the spacing between icon and username for the compact `UserLabelView`.
What it looks like currently:
Proposed change:
=> Compact UserLabelView spacing tweak

Mlem/App Constants.swift, Mlem/AppDelegate.swift, Mlem/Extensions/Color.swift, Mlem/MlemApp.swift, Mlem/Notifications/NotificationDisplayer.swift, Mlem/Temp Image Viewer/ImageSaver.swift, Mlem/Temp Image Viewer/ZoomableContainer.swift, Mlem/Views/Shared/Quick Look/QuickLookPreviewController.swift, Mlem/Views/Tabs/Search/SearchView.swift
This PR remove almost all of the references to UIKit. Most of these were nothing more than deleting the import, the photo saving required a change. I would appreciate if someone could check I did that correctly!
None, any functional change is a bug
Removing UIKit dependency and being 100% on SwiftUI would allow native Mac support someday.
=> Remove most imports of UIKit

Mlem/Views/Shared/Comments/Components/CommentBodyView.swift, Mlem/Views/Shared/Components/Components/InfoStackView.swift, Mlem/Views/Shared/Components/InteractionBarView.swift, Mlem/Views/Shared/Posts/Post Sizes/Compact Post.swift
This PR adds colors to the upvote/downvote icons and text for posts and comments when in compact views.
| | Before | After |
| - | - | - |
| Post | ![Simulator Screenshot - iPhone 15 Pro - 2023-12-08 at 00 01 48](https://github.com/mlemgroup/mlem/assets/1341797/28644aa5-dd59-483b-9299-832d48a15a13) | ![Simulator Screenshot - iPhone 15 Pro - 2023-12-08 at 00 00 38](https://github.com/mlemgroup/mlem/assets/1341797/79b7ad83-c390-424a-80df-2a99c267bb70) |
| Comment | ![Simulator Screenshot - iPhone 15 Pro - 2023-12-08 at 00 01 59](https://github.com/mlemgroup/mlem/assets/1341797/de922c1b-0f44-45ca-aeeb- …
=> Colorize voting icons and text in compact posts and comments

Mlem.xcodeproj/project.pbxproj, Mlem/API/Internal/HierarchicalComment.swift, Mlem/Extensions/String/String+ParseLinks.swift, Mlem/Extensions/View - Handle Lemmy Links.swift, Mlem/Models/Composers/Response Composers/Replies/ReplyToComment.swift, Mlem/Models/Composers/Response Composers/Reports/ReportComment.swift, Mlem/Models/Content/Post Model.swift, Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Comments/Components/CommentBodyView.swift, Mlem/Views/Shared/Comments/Components/Embedded Post.swift, Mlem/Views/Shared/Components/EasyTapLinkView.swift, Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
- closes #746 
This PR makes links embedded in post and comment content easier to hit by parsing them out of the body and aggregating them as nice easy-to-tap elements at the bottom. Links are given a title and caption according to the following schema:
- Raw links: destination host, full url
- Markdown links: markdown label, full url
- User links: /u/username, username@instance
- Community links: /c/community, community@instance
This PR also modifies the link handling code a little bit to properly allow navigation to communities using webfingers links (`!community@instance`)--Markdown parses those into `mailto:` links, so any `mailto:` link is parsed back into its webfingers format and resolved.
=> Made links easier to tap

Mlem.xcodeproj/project.pbxproj, Mlem/API/Models/Community/APISubscribedStatus.swift, Mlem/Extensions/EnvironmentValues/EnvironmentValues+FeedType.swift, Mlem/Models/Content/Community/CommunityModel.swift, Mlem/Models/Content/Post Model.swift, Mlem/Views/Shared/Links/Community/CommunityLabelView.swift, Mlem/Views/Tabs/Feeds/Feed View.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
- From community
This PR adds a subscription status indicator to the community label and a toggle in settings to enable/disable it. To support this, it adds logic to enrich the `CommunityModel` created within a `PostModel` with the subscription status.
=> Added subscribe indicator to community

Mlem/Views/Shared/Comments/Components/Embedded Post.swift
Fixed the embedded post link title alignment so that it's aligned to the leading edge rather than the center.
Before:
<br/>
After:
<br/>
=> Embedded Post Link Multiline Fix

Mlem/Views/Shared/Search Bar/SearchBar.swift, Mlem/Views/Tabs/Search/SearchView.swift
- closes #246 
This PR enables re-selecting the search tab to focus the search bar, provided that the feed is already scrolled to the top. I needed to do some slightly unsightly things to the SwiftUIX search bar to make the reselection work, as `let uiView = uiView as? _UISearchBar` never seems to execute and so the stock `.focused` doesn't work--the hack I've written doesn't have binding support, so *de-*selecting search requires some manual work, but since navigating off of the search tab usually requires dismissing the keyboard and therefore unfocusing search I don't think that's a huge problem.
https://github.com/mlemgroup/mlem/assets/44140166/60acbcc4-3b9a-4d53-acd5-6359d55a798c
https://github.com/mlemgroup/mlem/assets/44140166/8f904f4c-e4a2-45ec-9183-d9ab0c33d432
=> Search Reselection

Mlem/Views/Tabs/Feeds/PostFeedView.swift
Toggling "Hide Read" via the ellipsis menu in a feed wouldn't immediately work - you'd have to exit and re-enter the feed to see changes. Now, the feed refreshes immediately with the new setting applied. 
I don't really know why this fixes it, but it works 🤔
=> Fix toggling "hide read" not immediately updating

Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift, Mlem/Models/Content/Community/CommunityModel+SwipeActions.swift
When the `subscribed` property of `CommunityModel` is `nil`, it won't show the "Subscribe" action in context menus or swipe actions. This occurs when the `CommunityModel` was created from an `APICommunity` and not an `APICommunityView`, such as in the moderated communities list on a user profile. 
This PR fixes a bug where the "Favorite" action was still shown even when the "Subscribed" action was hidden. Now, both actions are hidden if the `subscribed` property is `nil`.
=> Fix community "Favorite" action being shown when it shouldn't

Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
The default value for this was inconsistent. I've set it to `false` everywhere, since the score is already shown in the Upvote/downvote widget.
Also added a footer to the "Interactions and info" section in post appearance settings to clarify that the settings only apply to Large & Headline posts. For Compact posts, the user's preferences are ignored and all of the info is shown.
=> Fix "Show score in info" setting default value inconsistency

Mlem/Enums/Settings/PostSortType.swift, Mlem/Views/Shared/Comments/Comment Item Logic.swift
The labels of the "Six Hours" and "6 Months" sort modes used inconsistent naming schemes. I changed the labels so that they all use numerals ("6") instead of words ("Six"). If you prefer they all use "Six", lmk and I'll change it. We should keep it consistent either way.
Also fixed a casing inconsistency with comment context menu actions. I changed "Undo upvote" to "Undo Upvote".
=> Fix Sort Mode Labelling Inconsistency

Mlem/Models/Content/Community/CommunityModel.swift
Fixed a bug where favoriting a community from the ellipsis menu in `CommunityView` wouldn't update the `CommunityModel` with the new state of `subscribed`, so the community would appear unsubscribed to until the view was exited and re-entered.
=> Community Favorite Fix

Mlem/Views/Tabs/Settings/Components/Views/Account/MatrixLinkView.swift, Mlem/Views/Tabs/Settings/Components/Views/Account/ProfileSettingsView.swift
A couple of bug fixes related to the Matrix ID page:
- Matrix ID input field always showed `""` when opening the page, not your existing Matrix ID.
- Pressing "cancel" the first time wouldn't do anything - you'd have to press it twice for the cancel to take effect.
I changed the description text (it seems Lemmy messaging doesn't go through Matrix as I previously thought) and also tweaked the appearance of the navigation link to show your matrix ID if you have one.
This is shown if you have a matrix ID:
This is shown if you don't:
=> Matrix ID Settings Bug Fixes & UI Tweaks

Mlem/API/Internal/HierarchicalComment.swift, Mlem/Views/Shared/Comments/Comment Item Logic.swift, Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Tabs/Feeds/Components/UserContentFeedView.swift, Mlem/Views/Tabs/Profile/UserFeedView.swift
- closes #892 
Fixes an issue where comment items in the user feed view would crash when updated due to no comment tracker being present in the environment. Comment tracker is now passed into the comment item directly as an optional, and all actions that require a comment tracker to updated are now guarded against its existence.
Longer term, comment voting logic needs to be moved into a `CommentModel` class that replaces `APICommentView`, but that's out of scope for 1.2.
=> Saved feed comment interaction crash fix

Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift
Adds support for the following link formats:
```
/u/user@lemmy.ml
/c/community@lemmy.ml
```
Bug was reported on mlemapp [here](https://lemmy.ml/comment/7989503). These are used frequently in the [!trendingcommunities@feddit.nl](https://feddit.nl/post/10189096) community.
Also, I removed the `"couldnt_find_object"` notification and made it just open in the browser instead in this case.
=> Link Resolution Fix

Mlem/Views/Tabs/Search/BubblePicker.swift
Minor improvement to the bubble-style picker that we use for tabs in communities/profiles/search. If you tap on a tab that is partially outside of the screen, it will now scroll so that the tab is fully visible. 
Currently, we only have enough tabs for this on a moderator's profile page.
https://github.com/mlemgroup/mlem/assets/78750526/c9c026ee-1f15-4289-97a3-3fe5cb8489c1
=> Bubble picker scroll-on-tap

Mlem/Views/Shared/Comments/Comment Item.swift
Previously you had to tap on the "show n replies" text to expand the replies, and tapping elsewhere on the button wouldn't work. Now, you can tap anywhere on the "show n replies" button to expand
=> Fix "Show n replies" button tap area

Mlem/Views/Tabs/Feeds/Feed Types/AggregateFeedView.swift, Mlem/Views/Tabs/Feeds/Feed Types/CommunityFeedView.swift, Mlem/Views/Tabs/Feeds/FeedsView.swift
- closes #903
This PR addresses some issues relating to sidebar navigation on iPad:
- Navigating between communities not working: addressed by giving the `CommunityFeedView` inside the navigation switch an explicit `id` so it redraws when the community changes
- Assertion failures on `FeedHeaderView` when navigating from an aggregate feed to a community: addressed by not drawing the header if selected feed isn't aggregate. 
Also adds some logic in `AggregateFeedView` to avoid superfluous post tracker refreshes when navigating to a community view.
=> fixed ipad sidebar navigation problems

Mlem/Views/Tabs/Feeds/Feed Types/AggregateFeedView.swift
- closes #905 
Fixes `.refreshable` on `AggregateFeedView` not accounting for the fact that the saved feed uses a different tracker.
=> fixed saved feed not refreshing

Mlem/Views/Tabs/Search/RecentSearchesView.swift, Mlem/Views/Tabs/Search/SearchView.swift
We now support searching instances, so I changed the search bar prompt from "Search Communities & Users" to "Communities, Users & Instances".
When we add post/comment searching, the prompt obviously wouldn't fit anymore. We'd have to go the Apple Music Route and write "Communities, Posts & More"
=> Updated search bar prompt

Mlem/ContentView.swift
- Closes #913 
Fixes an issue where the account switcher long press gesture wasn't appearing properly when updating from 1.1.2.
=> fixed account quick switcher not appearing until settings toggled

Mlem/Models/Trackers/SiteInformationTracker.swift
Fixed a bug where changing your avatar from outside of Mlem wouldn't update the avatar in Mlem's account switcher. Now, switching accounts causes the avatar to update
=> Fix changing avatar externally failing to update `SavedAccount`

Mlem/Views/Shared/Posts/Expanded Post.swift
On first app startup, the community and user instance captions on `CommunityLink` and `UserLink` were enabled, but not shown in `ExpandedPost` until the settings were toggled off and on again.
=> Fix Community/User instance caption app startup inconsistency

Mlem/Views/Tabs/Profile/UserView+Logic.swift
- closes #919 
This PR fixes a regression introduced by #874 where saved posts would appear twice in the feed. Saved posts were still being loaded and added to the tracker, but the feed itself was no longer filtering them out in the Posts or Overview tab.
=> fixed dupes in profile feed

Mlem/Models/Content/Post/PostModel+MenuFunctions.swift, Mlem/Models/Menu Function.swift, Mlem/Views/Shared/Components/Components/Menu Button.swift
1. Adds a "Developer Menu" to `PostModel` context menu and ellipsis menu (this only ever builds when `DEBUG` flag is enabled).
2. Adds `Toggle Read State` to developer menu.
3. Adds ability to build child menus using existing MenuButton and MenuFunction infrastructure.
=> Add developer menu to post model context menu and ellipsis menu.

Mlem/Models/Content/Post/PostModel+MenuFunctions.swift, Mlem/Models/Menu Function.swift, Mlem/Views/Shared/Comments/Comment Item Logic.swift, Mlem/Views/Shared/Comments/Comment Item.swift, Mlem/Views/Shared/Components/Components/Menu Button.swift, Mlem/Views/Shared/Posts/Expanded Post.swift, Mlem/Views/Shared/Posts/Feed Post.swift, Mlem/Views/Tabs/Settings/Components/Views/Accessibility/AccessibilitySettingsView.swift
Moved upvote/downvote/save/reply onto one row. Also moved the ellipsis menu of an expanded post to the toolbar. Pin and Lock are only shown in the expanded post.
=> Rearrange Menu Functions

Mlem.xcodeproj/project.pbxproj, Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift, Mlem/Logic/URLHandler.swift, Mlem/Navigation/Destination Values/SettingsValues.swift, Mlem/Views/Tabs/Settings/Components/SettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift, Mlem/Views/Tabs/Settings/Components/Views/Links/LinksSettingsView.swift
Adds an "Open in Reader" option that opens webpages in Safari's Reader Mode when available. 
I've moved all of the link-related settings from General into a new Links page. In future, we'll have even more link-related settings (see #639) so I think having a separate page for links is justified.
Closes #949
=> Auto-Reader Mode

Mlem/Views/Tabs/Feeds/Components/PostFeedView.swift
Steps to repro the issue this fixes:
- Scroll to "read" some posts in a feed
- Go back to the feeds page
- Re-enter the feed
- Posts that were previously "read" appear unread
=> Flush Mark Read Batcher on View Disappear

Mlem/Models/Settings/LayoutWidgets/LayoutWidget.swift, Mlem/Models/Trackers/LayoutWidgetTracker.swift, Mlem/Views/Tabs/Inbox/InboxView+Logic.swift
Also rewrote the piece of code that was causing the lint issue... I upgraded to Swiftlint 0.53.0 and it still complains about that part of the code; I'll look into it some more later
=> Fix interaction bar being reset to default when upgrading to 1.3

Mlem/Models/Content/Inbox/ReplyModel.swift, Mlem/Models/Trackers/Inbox/UnreadTracker.swift
This PR fixes the inbox count dropping below 0.
It also fixes the `.read()` call triggered by voting on a reply not executing on a delay and also using a background thread.
=> Prevent unread count from dropping below 0

Mlem.xcodeproj/project.pbxproj, Mlem/API/APIClient/APIClient+Instance.swift, Mlem/API/Requests/Site/BlockInstance.swift, Mlem/App Constants.swift, Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift, Mlem/Models/Content/Instance/InstanceModel+MenuFunctions.swift, Mlem/Models/Content/Instance/InstanceModel.swift, Mlem/Models/Content/User/UserModel+MenuFunctions.swift, Mlem/Views/Shared/Instance/InstanceView.swift
Added a "Block" action to the ellipsis menu in `InstanceView`. Due to an API limitation, the "block" action is only available when you visit the `InstanceView` from a community page or user page (on 0.19.4 and above), and not from search. I've [submitted an issue on the Lemmy repo](https://github.com/LemmyNet/lemmy/issues/4636) to hopefully resolve this limitation in future.
This PR doesn't add the block lists where you'll be able to unblock users/communities/instances - I'll do that in a follow-up PR
Closes #672
=> Block Instances

Mlem.xcodeproj/project.pbxproj, Mlem/API/Requests/Community/ListCommunities.swift, Mlem/Extensions/String/String+Alphabet.swift, Mlem/Extensions/String/String+StrippingDiacritics.swift, Mlem/Info.plist, Mlem/Models/Content/Community/Community List/CommunityListModel.swift, Mlem/Models/Content/Community/Community List/CommunityListSection.swift, Mlem/Views/Tabs/Feeds/Community List/CommunityListSidebarEntry.swift, Mlem/Views/Tabs/Feeds/FeedsView.swift, MlemTests/Community List/CommunityListModelTests.swift
- closes #958 
This PR fixes app slowdown when subscribed to hundreds of communities.
The slowdown was caused by `FeedsView` triggering unnecessary recomputations of the community sections, which required iterating over the list of subscribed communities several times and performing several filtering operations, many redundant.
To resolve this, I have implemented the following changes:
- Added a quick lookup set for subscribed and favorited communities
- Made `allSections` and `visibleSections` stored rather than computed, and they are recomputed only when `subscribed` or `favorited` changes
- Refactored section generation logic to avoid unnecessary filter calls (`allSections` and `visibleSections` are now built side-by-side)
- `CommunityListSection` now includes the list of communities …
=> Fixed app slowdown with many communities

Mlem/Extensions/View Modifiers/View+SwipeyActions.swift, Mlem/Icons.swift, Mlem/Models/Content/Inbox/CommentReportModel.swift, Mlem/Models/Content/Inbox/MessageReportModel.swift, Mlem/Models/Content/Inbox/PostReportModel.swift, Mlem/Models/Content/Inbox/RegistrationApplicationModel.swift, Mlem/Models/Settings/LayoutWidgets/LayoutWidget.swift, Mlem/Views/Tabs/Inbox/Item Types/InboxCommentReportView.swift, Mlem/Views/Tabs/Inbox/Item Types/InboxMessageReportView.swift, Mlem/Views/Tabs/Inbox/Item Types/InboxPostReportView.swift, Mlem/Views/Tabs/Inbox/Item Types/InboxRegistrationApplicationView.swift
- closes #1027 
This PR adds mod swipe actions to all moderator inbox items.
Due to there being no nice inverted "burn" icon, I made `purge` the second trailing action. For consistency, I have swapped its default widget location with `ban`.
=> Mod Swipe Actions

Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift, Mlem/Navigation/Destination Values/SettingsValues.swift, Mlem/Navigation/Routes/AppRoutes.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift, Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetView.swift, Mlem/Views/Tabs/Settings/Components/Views/Moderation/ModerationSettingsView.swift
- closes #1028 
This PR implements mod widget customization.
=> implemented mod widget customization

Mlem/Logic/BiometricUnlock.swift
Changed biometric login to use `.deviceOwnerAuthentication`, allowing users to input their device password instead. For some reason this is not built into the `.deviceOwnerAuthenticationWithBiometrics` API.
=> FaceID fix for locked out user

Mlem/App/Globals/Definitions/AppState.swift, Mlem/App/Logic/API/API Client/ApiClient.swift, Mlem/App/Views/Shared/Accounts/AccountListView.swift
Changes the way `ActiveAccount` is initialized:
- Guest mode and user mode now have two separate initializers
- The guest mode initializer just takes the `URL` of the instance rather than an `ApiClient`
This approach makes the behavior of the initializer more transparent, removes the possibility of initializing a user account with an `ApiClient` pointing to a different instance, and removes the need to spin up `ApiClient`s just to call the guest mode initializer.
=> [2.0] Proposed refinement to ActiveAccount initializer

Mlem/Views/Shared/Posts/Expanded Post.swift
- closes #1041 
Fixes #1041 where the issue was that the comment collapse animations could show the comments overlapping the post. By adding the `.clipped()` view modifier on the comments view inside of the post the comments no longer clip into the featured post when collapsed.
The linked issue (#1041) has a video of the issue, here is a similar video showing the fix.
https://github.com/mlemgroup/mlem/assets/1799888/98c7392c-ffc8-4346-966a-8927eae9fb54
=> Clip comment view in posts

Mlem.xcodeproj/project.pbxproj, Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/App/Views/Root/Tabs/Feeds/FeedsView.swift, Mlem/App/Views/Shared/ContentLoader.swift, Mlem/App/Views/Shared/ExpandedPostView.swift, Mlem/App/Views/Shared/Navigation/NavigationPage.swift
This PR updates `ExpandedPost` to be navigable using `AnyPost` (and therefore using any class in the `PostProviding` family)
It also contains a first iteration at how we can handle loading upgradable content in the form of `ContentLoader`. `ContentLoader` takes in an `Upgradable` (see aforementioned PR) and a `@ViewBuilder` that creates a view from the given `Upgradable`'s `MinimumRenderable` type. If the `Upgradable` doesn't conform to `MinimumRenderable`, a loading spinner is displayed while `upgrade()` is performed. If the `Upgradable` is at least `MinimumRenderable`, the view is displayed; if it is not fully `Upgraded`, then `upgrade()` is called.
This system lets us neatly handle displaying upgradable content regardless of its current upgrade status by simply wrapping it in a …
=> ContentLoader

Mlem/API/APIClient/APIClient+Post.swift, Mlem/Models/Content/Post/PostModel.swift, Mlem/Repositories/PostRepository.swift
In 0.19.4, Lemmy removed support for the `postId` parameter of `MarkPostReadRequest`. From 0.19.4 onwards, only the `postIds` parameter can be used. `postIds` was introduced in 0.19.0, but both `postId` and `postIds` were supported until 0.19.4.
Without this fix, an error notification is shown when opening a post or opening the image viewer on a 0.19.4 instance. This PR uses the `postIds` parameter instead of `postId` on instances running 0.19.0 or higher, which fixes the issue.
We should release a 1.3.1 patch with this fix. At the moment, 0.19.4 is in the release candidate stage; `lemmy.ml` is the only major instance running 0.19.4.
=> [1.3] Fix marking as read

Mlem.xcodeproj/project.pbxproj, Mlem/App/Constants/Icons.swift, Mlem/App/Globals/Definitions/AppState+transition.swift, Mlem/App/Globals/Definitions/AppState.swift, Mlem/App/Logic/HandleError.swift, Mlem/App/Models/ErrorDetails.swift, Mlem/App/Views/Root/ContentView.swift, Mlem/App/Views/Root/Onboarding/LandingPage.swift, Mlem/App/Views/Root/Tabs/Feeds/FeedsView.swift, Mlem/App/Views/Root/Tabs/Settings/AccountListSettingsView.swift, Mlem/App/Views/Root/TransitionView.swift, Mlem/App/Views/Shared/Avatar/AvatarView.swift, Mlem/App/Views/Shared/ListRow/AccountListRow.swift, Mlem/App/Views/Shared/ListRow/AccountListRowBody.swift, Mlem/App/Views/Shared/Toast/Toast.swift, Mlem/App/Views/Shared/Toast/ToastModel.swift, Mlem/App/Views/Shared/Toast/ToastView.swift
Closes #1065
The toggle for this is under the account list in settings. It's set to reload the feed by default. In the account switcher, you can swipe or long press to access the non-default behaviour.
I also fixed the quick switcher always showing a`.large` sheet, not the `.medium` sheet it's supposed to - this seems to be caused by the `ProgressView`, so I've disabled it for now.
Also made some tweaks the toast system to (hopefully) stop toasts from occasionally getting stuck and not going away.
=> Show transition on account switch

Mlem/App/Views/Shared/ContentLoader.swift
This PR fixes an issue where the `ContentLoader` could be triggered twice. The `upgradeState` variable has been replaced by an `AsyncSemaphore`.
=> Thread Safe Content Loader

Mlem.xcodeproj/project.pbxproj, Mlem/App/Views/Shared/MultiplatformView.swift
This PR introduces the `MultiplatformView`, a construct designed to streamline creating different views for different platforms. Its operation is very simple: it takes in two `View` closures, one to render for iPhone and one to render for iPad, and renders the one appropriate for the current platform.
```
var body: some View {
MultiplatformView {
contentForPhone
} pad: {
contentForPad
}
}
```
Ideally we would do this with compile-time checks to avoid the runtime conditional, but I can't seem to find a good way to check for iPadOS at compile time.
=> MultiplatformView

Mlem.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Mlem/API/APIClient/APIClient.swift, Mlem/Models/Composers/Response Composers/Replies/ReplyToMessage.swift
- closes #1096 
This PR fixes an issue where private messages failed to send due to them incorrectly sending to `.id` instead of `.userId`.
It also removes the unused deprecated person-based `sendPrivateMessage` method.
=> Fixed private messages not using correct id

Mlem/Models/Saved Account.swift, Mlem/Models/Trackers/Saved Account Tracker.swift, Mlem/Repositories/PersistenceRepository.swift, MlemTests/Persistence/PersistenceRepositoryTests.swift
Added compatibility for decoding Mlem v2's saved accounts. This ensures that the saved accounts aren't lost if the user downgrades from v2 to v1 (by leaving the beta).
=> [1.3] v2 `SavedAccount` compatibility
